### ISSUE TITLE
epilog failures at LLNL

### ISSUE THREAD

**Issue by gzjfn4** [IBM/CAST#123]
In the nvidia epilog, llnl getting lots of failures.

[root@sierra1133:epilog.d]# /admin/scripts/test_sierra_node
FAILED: sierra1133 Failed during cudaGetDeviceCount: initialization error

so on a compute node on sierra, say sierra1, there is a file /admin/scripts/test_sierra_node.cu

The script "test_sierra_node" is checking the state of the gpus on the system....what they find is that this code will fail for some nodes, after a job has finished....it means that no other jobs can use the GPUs unless the node is rebooted.

customer don't have a reproducer, but the hope is that somehow nvidia could determine why the node is stuck....we have plenty of example nodes for them to check on.

epilog failures that we're seeing on sierra 

#### CSM maintenance
compute:    "GPU 0 failed cudaMalloc 1":                                                            1: sierra3061
compute:    "IB CQE completion error 12":                                                           1: sierra1626
compute:    "SLOW GPU":                                                                             1: sierra1539
compute:    "epilog: FAILED: sierra1133 Failed during cudaGetDeviceCount: initialization error":    1: sierra1133
compute:    "epilog: FAILED: sierra1301 Failed during cudaGetDeviceCount: initialization error":    1: sierra1301
compute:    "epilog: FAILED: sierra1310 Failed during cudaGetDeviceCount: initialization error":    1: sierra1310
compute:    "epilog: FAILED: sierra1840 Failed during cudaGetDeviceCount: initialization error":    1: sierra1840
compute:    "epilog: FAILED: sierra1942 Failed during cudaGetDeviceCount: initialization error":    1: sierra1942
compute:    "epilog: FAILED: sierra2075 Failed during cudaGetDeviceCount: initialization error":    1: sierra2075
compute:    "epilog: FAILED: sierra2551 Failed during cudaGetDeviceCount: initialization error":    1: sierra2551
compute:    "epilog: FAILED: sierra2789 GPU 0 failed cudaMalloc 1: out of memory":                  1: sierra2789
compute:    "epilog: FAILED: sierra3053 GPU 0 failed cudaMalloc 1: out of memory":                  1: sierra3053
compute:    "epilog: FAILED: sierra3518 Failed during cudaGetDeviceCount: initialization error":    1: sierra3518
compute:    "epilog: FAILED: sierra3832 GPU 3 failed cudaMalloc 1: out of memory":                  1: sierra3832
compute:    "epilog: FAILED: sierra4151 Failed during cudaGetDeviceCount: initialization error":    1: sierra4151
compute:    "epilog: FAILED: sierra824 Failed during cudaGetDeviceCount: initialization error":     1: sierra824
compute:    "epilog: TEST_SIERRA_NODE failed with empty output":                                    1: sierra3797
compute:    "foxd: IB 2 missing":

**Comment by gzjfn4** [comment]
gordonc (IBM)
15 Jun 2018   9:14 AM

Hi James,

If I understand correctly, the script /admin/scripts/test_sierra_node failed outside of LSF. It seems the issue has not anything to do with epilog or LSF. Is the script from Nvidia? If so, then it might be a ticket for them. Can you please confirm so we may find the right person to handle the case?

Thanks,

Gordon

**Comment by gzjfn4** [comment]
gordonc (IBM)
19 Jun 2018   10:04 AM

Talked with Jin, we both think it's not an LSF issue. The case should be for CSM team. I'm transferring it to CSM team now.

**Comment by gzjfn4** [comment]
The SalesForce case # for this issue = TS001043457. However, I am learning that CSM (Cluster System Manager) is not a listed product in SalesForce for software problem management tickets.  According to Fernando Pizzano, CSM tickets should be logged into github at 'https://github.com/IBM/CAST/issues'

James

**Comment by fpizzano** [comment]
@gzjfn4 look like you are reporting a epilog failure, please contact epilog developer.

**Comment by adambertsch** [comment]
The issue here is that the GPU is stuck in a bad state.  The problem is not the script that detects the GPU is in a bad state.  The script, and the epilog system that runs it, are working fine.

Please close this CSM issue.  An issue needs to be opened in whichever IBM system is appropriate for determining whether we have a hardware problem in (all of our) GPUs, or a software problem in CUDA.  Thanks!

**Comment by gzjfn4** [comment]
Agreed. There is a hardware PMH opened for this issue -- PMH 26280,227,000.
