### ISSUE TITLE
hcdiag version file created by hcdiag/src/framework/CMakeLists.txt is untracked in git

### ISSUE THREAD

**Issue by pdlun92** [IBM/CAST#129]
In commit https://github.com/IBM/CAST/commit/dd1faed95a7ab6ea67be223b409b9ee00972f132

Since the `version.py` file is created directly from that `CMakeLists.txt` file when running `./scripts/configure.pl` during the build process, it is untracked by git.

So currently, if a user attempts to build CAST they wind up with a dirty git repo
after running build:
```
-bash-4.1$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	hcdiag/src/framework/version.py
```
easy enough to handle in the interim but needs to be addressed going forward

Two possible suggested solutions:
1. Create the file directly (i.e. not in the `CMakeLists.txt` file) and add it to git
2. Add it to the `.gitignore`

However, maybe there is another way to handle this

**Comment by tgooding** [comment]
Generated files should be placed at CMAKE_CURRENT_BINARY_DIR, instead of CMAKE_CURRENT_SOURCE_DIR.
