### ISSUE TITLE
csm_allocation_delete fails with rc=25 while allocation in to-running state

### ISSUE THREAD

**Issue by mattaezell** [IBM/CAST#14]
As of CAST 1.0, the new `to-running` state appears to be causing us problems in synchronization with LSF.  If a user starts an interactive job and Ctrl-C's out of it while the jobs is in `to-running`, LSF will issue a `csm_allocation_delete`.  This call will return `rc=25`, but LSF interprets that as "delete has already happened" and never tries again.  This leaves an orphan allocation.

Ideally, the `csm_allocation_delete` would be queued and processed as soon as the prologue finishes.

**Comment by fpizzano** [comment]
@mattaezell and @verolero86
Base on yesterday conversation, @jma562 made changes to how LSF handle `csm_allocation_delete` faulire with a retry mechanism.

At the moment CSM is not planning to introduce queuing to `csm_allocation_delete`.
