### ISSUE TITLE
dev branch broken

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#148]
```
CMake Error at csmdb/sql/CMakeLists.txt:51:
  Parse error.  Function missing ending ")".  End of file reached.

```

Bill says he pushed a fix to master. 

**to do:** 
- [ ] cross merge dev / master.

this should bring dev up to date, which will include the fix. then dev can build again. 

I'll do this tomorrow morning, but if someone in a later timezone would like to do this, then it would be a nice surprise when I come into work tomorrow.

**Comment by lasch** [comment]
```
git cherry-pick c2f46e2
```
done.

**Comment by lasch** [comment]
ok. I guess, that was incomplete. The request was for a cross-merge... Sorry.
Merged latest master into dev(elopment). Since there was no additional commit to dev, they should be in sync as of now.

**Comment by NickyDaB** [comment]
> Since there was no additional commit to dev, they should be in sync as of now.

But it says 2 commits ahead?

**Comment by NickyDaB** [comment]
oh, I think I know what happened. next time for this situation:
on IBM CAST repo
in the console
`git fetch`
`git checkout development`
`git merge master`
That will bring all the updates from master into dev. a simple catch up so to speak. this will also eliminate that extra commit. you can also reverse the process to put the stuff from dev into master.

**Comment by NickyDaB** [comment]
ill leave this alone for now (the 2 commits ahead thing), but next time it gets out of sync I'll put it back to 0|0

**Comment by lasch** [comment]
I don't see which commits would be ahead. From looking at the tree, I think they are in perfect sync.

**Comment by lasch** [comment]
No diffs.
```
$ git diff CAST/master
$ 
```

**Comment by tgooding** [comment]
github says its these commits:
```
Commits on Jul 09, 2018
cmake - missing ) correction.   e8601a2
cross merge with master to sync dev branch.   3c6220b
```

**Comment by NickyDaB** [comment]
yeah, essentially the code is the same, but you added in a commit with the cherry pick and then another commit when you merged.

**Comment by lasch** [comment]
I see. Well, I guess, you'll never be able to sync them without any commit in advance, unless, you do a "forward-only" commit and put both branch pointers on the same commit?

@NickyDaB I can do that. Would be easy to do.

**Comment by lasch** [comment]
I merged and synced the 2 branches now. They should be pointing to the same commit.
