### ISSUE TITLE
bsub hangs when bad -alloc_flags specified

### ISSUE THREAD

**Issue by gzjfn4** [IBM/CAST#149]
I was testing providing user level flags to CSM via bsub and when I put in a flag that is not already defined in the privileged_prolog file the allocation just hangs until I hit control-C.

[foxd@butte5:butte]$ bsub -nnodes 2 -Is -W 60 -G guests -q pbatch -alloc_flags "myf" /bin/bash Job <12922> is submitted to queue <pbatch>.
<<Waiting for dispatch ...>>
^CJob <12922> is being terminated

Below is the kind of message that shows up in the csm_master.log.

Seems like this is a bug and the bsub should just fail with some kind of messages about a flag being invalid.

James unless Py or Adam chime in saying this is a known issue I suggest we open a ticket on this with IBM. In summary the bsub should not just hang (I waited over 5m) and should fail and provide some kind of message that the attempted bsub is bad.

2018-07-09 12:58:21.199021     csmapi::info     | [2111670351]; Allocation ID: 0; Primary Job Id: 12922; Secondary Job Id: 0; Message: Reques
ting allocation in database; 
2018-07-09 12:58:21.230401     csmapi::info     | [2111670351]; Allocation ID: 8662; Primary Job Id: 12922; Secondary Job Id: 0; Message: Res
erving nodes in database; 
2018-07-09 12:58:21.914307     csmapi::error    | [2111670351]; NetworkMessageState: An error was detected while recieving a Network Message.
2018-07-09 12:58:21.916204     csmapi::error    | [2111670351]; NetworkMessageState: An error was detected while recieving a Network Message.
2018-07-09 12:58:28.469855     csmapi::info     | [2107216980]; csm_node_resources_query_all start
2018-07-09 12:58:28.475049     csmapi::info     | [2107216980]; csm_node_resources_query_all end
2018-07-09 12:58:29.225539     csmapi::error    | [2111670351]; McastResponder: The mulicast had errors.
2018-07-09 12:58:29.262756     csmapi::error    | csm_allocation_create[2111670351]; Allocation ID: 8662; Primary Job Id: 12922; Secondary Jo
b Id: 0; csm_allocation_create[2111670351]; butte11; Privileged script execution failure detected. Error code received: 1 csm_allocation_crea
te[2111670351]; butte22; Privileged script execution failure detected. Error code received: 1 ---- End Remote Errors ----    ---- End Remote 
Errors ---- ---- End Remote Errors ----    ---- End Remote Errors ---- ; Message: Allocation is being reverted; -3 : MTC unreachable twice | 
-2 : MTC unreachable on primary attempt | -1 : MTC unreachable on final attempt | >0 : Remote node reported an error; butte11 : 17;butte22 : 
17; ; Message: Allocation was successfully reverted;

**Comment by gzjfn4** [comment]
@fpizzano 

I had originally opened case with LSF support team via SalesForce ticket # TS001121817.

However, LSF team is saying this is a CSM issue.

Hi James,

The flags specified in -alloc_flags are purely for CSM, LSF just transfer them to CSM and does not process them at all. Could you please log the issue on CSM? As I know CSM issues are logged in github.

Thanks,

Gordon

**Comment by gzjfn4** [comment]
customer believes this is really an issue about the interface between CSM and LSF.  When you specify invalid flags, CSM returns a failure, but LSF just keeps trying.  I don’t think there is any notion of a “fatal” event versus something that should be retried.  We will eventually need the two camps to actually talk to each other -- in reference to CSM and LSF support teams.

**Comment by gzjfn4** [comment]
LSF team thinks CSM allocation should return failure when the alloc_flags are invalid, since LSF may not be aware of the valid alloc_flags. So their perception is CSM needs to fix it, LSF might need no change. But let's keep the case open (TS001121817) until CSM team confirms that.

**Comment by jma562** [comment]
This is not bsub hung, when an interactive job is pending, interactive bsub will wait until you ctrl+c to terminate or bkill. This is standard LSF behavior, e.g., if you submit a job simple with bsub -R "select[mem<0]" -Is /bin/sh, this job will pending for ever, and bsub interactive session will keep open until you ctrl+c out of it.
e.g. in the following example, there's no host available, then bsub interactive session stays in 
Waiting for dispatch until you ctrl+c out of it.
 bsub -Is /bin/sh
Job <5055> is submitted to default queue <interactive>.
<<Waiting for dispatch ...>>
^CJob <5055> is being terminated

It's just like you bsub a batch job and this is pending or dispatched->failed->pending again, this job stays in the system.

It would be a new behavior enhancement if you ask for interactive bsub wait time out.

**Comment by jma562** [comment]
You can always bjobs pending reason and bmod the job in order for it to be able to run instead of resubmit the job.  If you prefer always resubmitting it, please be aware that the new job loses its pending time priority.

**Comment by rgoldino** [comment]
If I understand correctly, LSF can implement the correct behavior (terminate the job instead of hang) if CSM can return different error codes differentiating between recoverable and non-recoverable errors.  @fpizzano does CSM currently send a unique error code for this type of failure (invalid value in alloc_flags) or does the API just return the same error code for all failures?

**Comment by jma562** [comment]
The flags come in different name from site to site.
The most efficient way is to block mis-spelt flags at job submission time at bsub time via esub, thus, such jobs won't go through scheduling cycles, and dispatched, and get  rejected by CSM. (the job may be pending for some time before it gets dispatched and such error detected by csm).
Personally I think it is better than delaying the check and waiting for CSM to detect such errors because again,LSF will call CSM API only until the job is dispatched (could be hours later).

Fernando and I had a discussion,  we will enhance LSF and CSM to further fine tune error handling by introducing more CSM error code and error class. It will help this specific case but I think the best way is to detect and reject job submission by esub instead waiting for CSM to detect and reject.

**Comment by mew2057** [comment]
This was fixed in Release 1.4.0 PR #382. Moving to Verify.

**Comment by mew2057** [comment]
@pdlun92 and @fpizzano we need to verify this no longer happens and close this issue.
