### ISSUE TITLE
libcsmpam.so inappropriately uses 'session' to perform 'account' function

### ISSUE THREAD

**Issue by adambertsch** [IBM/CAST#15]
libcsmpam.so is currently performing account function in the session part of the module.  There are three issues to fix by separating these two functions.

1) This can cause a pam stack to initiate other session functions inappropriately when account should not have succeeded in the first place.
2) This module inappropriately prints information related to authentication during session (printing is not allowed during authentication) and this can break protocols such as rsh or scp that rely on connecting stdout/stdin to a program running on the remote host.  
3) It is desirable to be able to re-order the account pam stack separately from the session pam stack (which in libcsmpam is used to set up cgroups).  

We are currently trying to work the CAST corporate contributor agreement through our legal department.  If we are successful we can probably submit a pull request to fix these issues.

**Comment by adambertsch** [comment]
I haven't quite been able to wrap my head around all of the serialization plumbing yet.  I need to split CSM_CMD_cgroup_login in to two separate CSM commands.  One that checks the active list and return success/fail to be called by pam_sm_acct_mgmt.  That is to say, everything the current CSMICGROUPLogin does, except for calling migrate_pid(), and removal of the printf.  The new class needs to perform most of the same initialization as CSMICGROUPLogin in order to call migrate_pid().  None of these modules should printf, the pam stack can output using pam_echo if it's truly desired.

**Comment by adambertsch** [comment]
I was considering something like the flag approach as well.  What I couldn't convince myself was that there would never be a time when one might want to migrate pids, but not have to return an error if the current user didn't have an allocation.

Basically pseudocode like this:

account
    success if root
    fail if unable to initialize api
    success if on active list
    success if on white list
    fail

session
    migrate if on active list
    success

This way, if we call session for someone not on the active list, we don't have to fail and the logic ends up much cleaner.  accounts on the white list, or other pam module successes (that happened during account) can still cleanly pass through our session function.

Is this cleanliness worth the extra effort to do it right the first time?  I am open to being convinced that it is not especially since I'm going to have to learn a lot of stuff in order to add the APIs.  On the other hand, adding the APIs will be an excellent primer for future work.

**Comment by mew2057** [comment]
Yeah I think the edit might be the path to take to follow the flag approach. Since the session code shouldn't care about the response from the migrate. I'm not 100% convinced that we need two APIs in this case simply because the flag will work well for the use case. 

The session behavior is a superset of the account behavior and having two APIs for the behavior might result in duplicate code. If we reuse the same backend handler then we're just making the flag be the command id and adding additional API to maintain documentation and run tests on (even if the backend is the same the frontend may have issues).

**Comment by adambertsch** [comment]
I'm just about there, and it's the plumbing again.

I added the migrate_pid flag to the struct, but can't generate the headers now.  I followed the steps in the readme for adding a new def file, but apparently steps for changing an existing def are different.  Do I need to "ship" a new API version using regenerate_headers to cause this to work?

The only def file change I have is:
```
[bertsch2@butte5 CAST]$ git diff ./csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def
diff --git a/csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def b/csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def
index f95f95e..ca6d9de 100644
--- a/csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def
+++ b/csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def
@@ -54,6 +54,7 @@ CSMI_VERSION_START(CSM_VERSION_0_4_1)
 CSMI_STRUCT_MEMBER(int64_t, allocation_id,  BASIC, ,   -1, ) /**< Allocation ID to prefer (rejected if >0 and not found in daemon). */
 CSMI_STRUCT_MEMBER(pid_t,             pid,  BASIC, ,    0, ) /**< The process id to push to the allocation cgroup. */
 CSMI_STRUCT_MEMBER(char*,       user_name, STRING, , NULL, ) /**< User name for logging in. */
+CSMI_STRUCT_MEMBER(char,      migrate_pid,  BASIC, ,    0, ) /**< Flag to migrate pid in to cgroup if true. */
 
 CSMI_VERSION_END(7abc0fd516f773957ae20e5d59fa90e2)
 #undef CSMI_VERSION_START
[bertsch2@butte5 CAST]$ 
```
The errors spit out by regenerate_headers are:
```
[bertsch2@butte5 CAST]$ csmi/include/struct_generator/regenerate_headers.sh   
Regenerating headers (should take about 2 seconds)
Completed header generation for Launch; Failures: 0; Missing: 0;
Completed header generation for Common; Failures: 0; Missing: 0;
Completed header generation for Diagnostic; Failures: 0; Missing: 0;
Completed header generation for Burst Buffer; Failures: 0; Missing: 0;
Completed header generation for RAS; Failures: 0; Missing: 0;
Failure Detected in ../csm_types/struct_defs/wm/csm_cgroup_login_input.def!
ERROR: Modifications were detected in the 1025 version block.Indicates a struct field was renamed, reordered or had its type changed.
Completed header generation for Workload Management; Failures: 1; Missing: 0;
Completed header generation for Inventory; Failures: 0; Missing: 0;
Completed with errrors.
[bertsch2@butte5 CAST]$ 
```

**Comment by adambertsch** [comment]
I'm still working on build and test, but [here](https://github.com/adambertsch/CAST/commit/3f6beae0b4e25a752e0290108d38a2684335b2e8) is what I've done so far.  Let me know if I've destroyed the world too badly thus far.
