### ISSUE TITLE
hcdiag clobbers cluster configuration file on install

### ISSUE THREAD

**Issue by robers97** [IBM/CAST#186]
Installing the hcdiag rpm clobbers 
/opt/ibm/csm/hcdiag/etc/clustconf.yaml

This is one of the main setup files for a cluster and copying it over is a big annoyance that has led to failing diagnostics to two clusters.  Admin have heavy eyes; they deserve a one line RPM change to avoid this situation.

**Comment by sanomiya** [comment]
Installing as clustconf.yaml.sample.
