### ISSUE TITLE
hcdiag chk-nvidia-vbios fail on P8 IST

### ISSUE THREAD

**Issue by JamesMartine** [IBM/CAST#214]
On the Power8 IST cluster, the chk-nvidia-vbios test is failing with what seems like some sort of a Perl error

`
[root@c660csm01 hcdiagrun]# cat /tmp/180815140548460698/chk-nvidia-vbios/cn21-2018-08-15-14_05_50.output
`
`
 Running chk-nvidia-vbios.sh on cn21, machine type 8335-GTB.
 nvidia-smi --query-gpu=gpu_name,gpu_bus_id,vbios_version --format=noheader,csv 2>/tmp/RmJaFr3m2R/stderr
`
`
 Can't "next" outside a loop block at ./chk-nvidia-vbios.pm line 118.
 Remote_command_rc = 255
`

**Environment (please complete the following information):**
 - Machine c660csm01 P8 IST
 - Version CSM 1.2.0

**Issue Source:**
hcdiag tests are being ran on the Power 8 Service Pack to test it and this seems like an issue for the test. Maybe Perl levels are not what they should be but there is no specification for Perl in the CoralDiagnostic 1.2.0 Documentation

**Comment by sanomiya** [comment]
Please update clustconf.yaml file.

**Comment by JamesMartine** [comment]
I have updated the clustconf.yaml file now with the following information which matches what the test returns:
```
    gpu:
      device: "Tesla V100-SXM2-16GB"
      vbios: "86.00.26.00.02"
```
However, the test still comes back with a fail:
```
[root@c660csm01 hcdiagrun]# cat /tmp/180816125840464522/chk-nvidia-vbios/cn6-2018-08-16-12_58_42.output
 Running chk-nvidia-vbios.sh on cn6, machine type 8335-GTB.
 nvidia-smi --query-gpu=gpu_name,gpu_bus_id,vbios_version --format=noheader,csv 2>/tmp/bldZjibZoM/stderr
 (ERROR) cn6: invalid vbios: Tesla P100-SXM2-16GB,86.00.41.00.01; expected: Tesla V100-SXM2-16GB, 86.00.26.00.02
 (ERROR) cn6: invalid vbios: Tesla P100-SXM2-16GB,86.00.41.00.01; expected: Tesla V100-SXM2-16GB, 86.00.26.00.02
 (ERROR) cn6: invalid vbios: Tesla P100-SXM2-16GB,86.00.41.00.01; expected: Tesla V100-SXM2-16GB, 86.00.26.00.02
 (ERROR) cn6: invalid vbios: Tesla P100-SXM2-16GB,86.00.41.00.01; expected: Tesla V100-SXM2-16GB, 86.00.26.00.02
 chk-nvidia-vbios test FAIL, rc=1
 Remote_command_rc = 1
```

It seems like there is no space in between what the test is getting from the node, but there is one space from what it is pulling from the clustconf.yaml file

**Comment by sanomiya** [comment]
Looks like you have a mixed environment when it comes to gpu bios.
```
[root@c660csm01 chk-nvidia-vbios]# xdsh /cn.*,-cn23 nvidia-smi --query-gpu=gpu_name,gpu_bus_id,vbios_version --format=csv |xcoll 

====================================
cn5,cn6
====================================
name, pci.bus_id, vbios_version
Tesla P100-SXM2-16GB, 00000002:01:00.0, 86.00.41.00.01
Tesla P100-SXM2-16GB, 00000003:01:00.0, 86.00.41.00.01
Tesla P100-SXM2-16GB, 00000006:01:00.0, 86.00.41.00.01
Tesla P100-SXM2-16GB, 00000007:01:00.0, 86.00.41.00.01

====================================
cn7,cn15,cn3,cn22,cn14,cn21,cn10,cn13,cn11,cn17,cn4,cn18,cn16,cn19,cn2,cn12,cn1,cn9
====================================
name, pci.bus_id, vbios_version
Tesla P100-SXM2-16GB, 00000002:01:00.0, 86.00.26.00.02
Tesla P100-SXM2-16GB, 00000003:01:00.0, 86.00.26.00.02
Tesla P100-SXM2-16GB, 00000006:01:00.0, 86.00.26.00.02
Tesla P100-SXM2-16GB, 00000007:01:00.0, 86.00.26.00.02
```

There are two ways to see the test PASS:
1. Create another case statement in the clustconf.yaml file, just with  the nodes: cn5 and cn6,
and change the gpu->vbios to 86.00.41.00.01. Remove cn5 and cn6 from the existent case.
2. Upgrade the gpu vbios of cn5 and cn6  to 86.00.26.00.02, which I believe it is the latest and greatest (need confirmation). 

It seems that all machines in your cluster are similar. So I don't see a reason why not do 1. 
I Diag is doing what is supposed to do in this case :-)

**Comment by JamesMartine** [comment]
Ahh, you're right. I made that small change to the clustconf.yaml file and now we have it passing on all except those 2 nodes, but we have no reason to think that the test is not working as intended since they actually have a different vbios. Thanks.
