### ISSUE TITLE
hcdiag chk-idle-state failing on P8 IST cluster

### ISSUE THREAD

**Issue by JamesMartine** [IBM/CAST#216]
On the P8 IST cluster, chk-idle-state has been failing on all nodes for this reason:

```
[root@c660csm01 hcdiagrun]# cat /tmp/180816151019682717/chk-idle-state/cn21-2018-08-16-15_10_21.output
 Running chk-idle-state.sh on cn21, machine type  8335-GTB.
 CPUidle driver: powernv_idle
 CPUidle governor: menu
 analyzing CPU 0:

 Number of idle states: 2
 Available idle states: snooze Nap
 snooze:
 Flags/Description: snooze
 Latency: 0
 Usage: 2526120
 Duration: 132111091
 Nap:
 Flags/Description: Nap
 Latency: 0
 Usage: 1399969
 Duration: 64264299643
 ERROR: Number of idle states, expecting: 3, got: 2
 chk-idle-state.sh test FAIL, rc=2
 Remote_command_rc = 2
```

**Environment (please complete the following information):**
 - Machine c660csm01
 - Version CSM 1.2.0

**Issue Source:**
This is one of the final tests needed to pass for the hcdiag tests for the P8 Service Pack

**Comment by sanomiya** [comment]
This test was to check a special setting for P9 for HPC. The effect of that setting is to hide the stop0 and stop0_lite states ( which  requires installing an appropriate firmware image and by making a one-time-only nvram setting).
It does not apply to P8. I will add  a message, and return PASS if P8.

**Comment by sanomiya** [comment]
Modified the code to check if P8, print a message and FAIL.
Changes checked in.

**Comment by JamesMartine** [comment]
Running this test now produces on the IST P8 cluster produces:
```
[root@c660csm01 hcdiagrun]# cat /tmp/180820153025279413/chk-idle-state/cn21-2018-08-20-15_30_26.output
 This test applies only to Withersppon, P9 machines.
 Remote_command_rc = 1
```
This test is now working as intended. Thanks.
