### ISSUE TITLE
Option to not put services in CSM system cpuset

### ISSUE THREAD

**Issue by fpizzano** [IBM/CAST#221]
**Summary:**
There is evidence that GPFS (and possibly other services) might not perform well when isolated to only the CSM system cpuset cores. An option needs to exist to allow services to stay on the CSM allocation cpuset cores. 

**Is your feature request related to a problem? Please describe.**
Problem Report number: 37957

**Comment by fpizzano** [comment]
Adding @miidon @verolero86 and @mattaezell

**Comment by mew2057** [comment]
Just as an initial spec for this issue, we will need to implement a mechanism for building a process tree, then a mechanism for disabling the migration of processes based on either process owner or executable. It's possible to do, but we're going to need to devote some man hours in researching and write up a spec for how to carry this operation out.

We might want to consider this defect an epic then make several issues separating the features to track this a little nicer.

**Comment by mew2057** [comment]
Closing this issue, as the new cgroup mechanism addresses this.
