### ISSUE TITLE
Python CSM API wrappers

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#238]
**Summary:**
Python CSM API wrappers. Feature requested by labs and by @fpizzano 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Issue Source:**
Reasoning for opening this issue; a description of why this issue was opened; a link to another thread that spawned the need for opening this issue.

**ToDo:**
- [ ] get original spec for this request and better fill in the above.

**Comment by mew2057** [comment]
There's a fair amount of headway that's been made on this process using  
[boost python bindings](https://wiki.python.org/moin/boost.python/GettingStarted). The key is that this python binding is supposed to be a python binding of the C API.
