### ISSUE TITLE
Invalid JSON syntax in CSM transaction log

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#253]
In the transaction log, CSM is not properly JSON encoding some (all?) strings.  This results in transactions cannot be parsed by logstash, and therefore do not appear in the elasticsearch database.

We are seeing this bug manifest itself in the allocation-step transaction type in the value string of the "environment_variable" field.  Some environment variables contain newlines.  CSM is putting these newlines directly in the document without JSON encoding them.  Raw newlines in the middle of strings are not valid in JSON.

We need CSM to properly encode all strings into valid JSON form before putting them in the transaction log JSON documents.

**Comment by mew2057** [comment]
I've got a tentative fix ready, I need to do some testing still on it. I've added a new function to the json generator to escape json control characters. Additionally, I've added a filter in the logstash configuration to drop malformed json entering the pipeline. I need to run some basic tests on it, but it should easily make the 1.3.0 drop. 

@pdlun92 we're going to need to create a test case for this which purposefully injects control characters and verifies the output in bds. We can talk in person later.
