### ISSUE TITLE
build expects to write to /opt/ibm

### ISSUE THREAD

**Issue by adambertsch** [IBM/CAST#26]
The build system expects to be able to write to /opt.  We really should be installing to some alternate path and then building packages from there, not trying to install in the system default location.  This enables two really important capabilities.

1) Ability to build as non-privileged user (someone who can't write to /opt).
2) Ability to build new packages without overwriting an existing install on the same node.

```
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/g/g0/bertsch2/src/build/CAST/csmconf/csm_aggregator.cfg" to
  "/opt/ibm/bin/csm_aggregator.cfg".
```

**Comment by besawn** [comment]
I think `"build package noinstall"` and `"rebuild package noinstall"` will do what you want.

The difference between `"build"` and `"rebuild"` is that rebuild also incorporates a clean up step first to force all objects to be rebuilt.

Can you try those and confirm if that is the behavior you are looking for?

**Comment by tgooding** [comment]
You'll need to use noinstall when building RPMs.

**Comment by adambertsch** [comment]
Perhaps noinstall should be the default, and you should only attempt to overwrite system files if install is explicitly stated?

**Comment by adambertsch** [comment]
By the way, it did what I wanted it to with rebuild package noinstall

**Comment by tgooding** [comment]
There certainly could be better ways to do it.  

Way back when, I recall difficulties juggling install, package, package_source, and component-level build targets.  Cmake made (makes?) some unfortunate hardwired assumptions about how it would call cpack for install that made things fun.

**Comment by adambertsch** [comment]
You can close this issue, since it's possible to do what was desired.  Thanks for taking the time to educate.
