### ISSUE TITLE
CSM job launch breaks at scale

### ISSUE THREAD

**Issue by adambertsch** [IBM/CAST#261]
**Describe the bug**
CSM job launch appears to work at 1024 nodes, while failing at 2048 nodes.  SSH job launch works.

**To Reproduce**
[bertsch2@sierra4362 ~]$ time bsub -q pbatch -G guests -nnodes 2048 -core_isolation 2 -Is lrun -T1 hostname
Job <188153> is submitted to queue <pbatch>.
<<Waiting for dispatch ...>>  
<<Starting on sierra4371>>
Error negotiating connection with pmix server. read() -1. errno [104] Connection reset by peer
Error initializing RM connection. Exiting.

real    0m44.329s
user    0m0.064s
sys     0m0.004s
[bertsch2@sierra4362 ~]$ cat .jsm.conf
JSMD_LAUNCH_MODE=csm
[bertsch2@sierra4362 ~]$ 

A collection of compute nodes (approximately 32 per job) end up with a csmd process zombie (unreaped) owned by the user, with a parent of the root csmd.  It appears that the root csmd never calls waited to reap the child when this particular failure happens.  Our epilog catches this with the following message.

"epilog: TIMEOUT: tasks still running!  Last one 'Zombie UID 45153 (bertsch2) '[csmd]''":

```
[root@sierra2143:~]# ps -ef |grep csmd
root      88562 137517  0 03:20 ?        00:00:00 /opt/ibm/csm/sbin/csmd -f /etc/ibm/csm/csm_compute.cfg
bertsch2  88563  88562  0 03:20 ?        00:00:00 [csmd] <defunct>
root     131249 130836  0 03:30 pts/0    00:00:00 grep --color=auto csmd
root     137517      1  0 Sep13 ?        00:02:30 /opt/ibm/csm/sbin/csmd -f /etc/ibm/csm/csm_compute.cfg
[root@sierra2143:~]# exit

```
**Expected behavior**
I would expect the job to actually run.

**Screenshots**
See above.

**Environment (please complete the following information):**
sierra
CSM 1.2.1-768

**Additional context**
N/A

**Issue Source:**
Acceptance testing.

**Comment by mew2057** [comment]
Today a I remember the behavior of this particular API is to run, call JSRUN and then exit. We fork twice to effectively perform a nohup and return. 

This mechanism was by design as jrun could run for an arbitrary length of time. Could the unreaped process be a hung jsrun instance?

Also it might be worth it for us to cache any pids we fork for an allocation and run a kill when the allocation or step is removed. @lasch does the daemon have any mechanism for handling something like this today?

**Comment by lasch** [comment]
@mew2057 No, we don't have any caching feature yet. Most of the daemon-wide status info is pushed into DaemonState. Lets discuss the options in our next meeting.

**Comment by adambertsch** [comment]
Note that my primary concern here is that csm launch crashes instead of launching jobs.  The fact that it leaves some zombies after is just icing on the cake that should likely also be fixed.

**Comment by jjhursey** [comment]
The JSM team has been engaged on this today. We have some leads that we are investigating.

**Comment by mew2057** [comment]
I'm looking into the zombies from the CSM perspective to see if we can reap when the create or delete comes through on non shared allocations.

**Comment by mew2057** [comment]
Thinking about the Reap, we could add a timeout to the options supplied to the API or use the daemon timeout where the forked process could reap itself if the value is exceeded.

**Comment by mew2057** [comment]
I've added some logging to the fork and exec to track what's happening.  While I was working on this I realized that the cgroup removal code should handle reaping of the processes, but I need to run some tests. @pdlun92 We should work out a generic script that waits indefinitely or gets deadlocked for a test case which sees if the pid is killed by the cgroup removal.

**Comment by mew2057** [comment]
We have some debug improvements and an improved waiting algorithm for the cgroup migration here:  #288
