### ISSUE TITLE
Invalid JSON in CSM archive json files

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#267]
The csm_allocation_history.archive.*.json and csm_step_history.archive.*.json files frequently contain invalid JSON, similar to issue #253.

This time though, the problem is usually double-quotes that appear in a user-specified string rather than newlines.  Here is a small excerpt from a type db-csm_allocation_history line:

`"user_script":"pwd;date;ls -l;#echo \\"Starting node sanity tests\\";#lrun -T 1 find_zombies;`

(the value continues, but I'm just showing the beginning where the first json error occurs for brevity)
Note that the user of double-quotes in the _value_ of the user_script key.  The double-quotes here are not properly escaped, and that make either beats or logstash incapable of parsing the json correctly, so the document does not appear in elasticsearch correctly either.

I skimmed the db archiving scripts involved, and I could be wrong, but it looks like this uses a different data collection path that won't be addressed by issue #253.

**Comment by mew2057** [comment]
This one shouldn't be too bad I think @williammorrison2  wrote this but I can take a look too. This *might* be a bug how we write the postgres dump to the file.

**Comment by mew2057** [comment]
Fix is now in mainline moving to verify.

**Comment by morrone** [comment]
I tried patching the one line into the running system, and if anything it seems to have made things worse.  Now we get entries that start like this:

`{"type":"db-csm_allocation_history","data":${"history_time":"2018-`

and end like this:

`,"archive_history_time":null}$}`

And, of course, those dollars signs aren't valid syntax.  Is there actually more to the fix than that one line?

**Comment by mew2057** [comment]
I have a new fix:

```
sed -i "s:([\b\f\n\r\t\"\\):\\\1:g" ${swap_file}
```

That should be added before the `awk -v table="$table_name"` line.

**Comment by morrone** [comment]
Are you maybe missing a right-bracket in that expression?

**Comment by mew2057** [comment]
Yep, fixed. Thanks for the catch.

**Comment by morrone** [comment]
That sed script does not seem to have solved the problem.  I see lines from csm_step_history.archive.*.json that are being broken up into multiple lines before or inside logstash. T

Here is a section where a break occurs twice:

` eval $($LMOD_CMD bash \\"$@\\");\\n [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\\n} BASH_FUNC_ `

And here is one of the bad entries that logstash logs:

{"input":{"type":"log"},"message":" [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)","@version":"1","@timestamp":"2018-09-28T22:46:21.216Z","tags":["transaction","beats_input_codec_json_applied"]}

You can see that "message" is the section that appear between the two newlines in the csm_step_history.archive.2018-09-28.json file.

Note that when I try to run just this line through a json parser in python (I just cat the line to "python -mjson.tool"), it also thinks that the produced output is improper json, but it balks at some of the double-quotes that are now not properly escaped.  Some of the double quotes are preceded by two backslash characters now, which I assume translate into a single literal non-escaping backslash, so that re-exposes the double quotes that used to be properly escaped.

So I don't suspect that a simple regex over the entire string is going to work here.

**Comment by mew2057** [comment]
Are the new lines in the database record unescaped? Can you copy the produced json ? One or two failing records should be sufficient.

**Comment by morrone** [comment]
The part above where I said "Here is a section where a break occurs twice" is a part of a line from the produced json file.  It shows the exact section where the json is not escaped in a way that results in a single message turning up in filebeats and/or logstash.

The full line in the json is gigantic.  If you really think the excerpt from the line is not sufficient for some reason, I can check to see if I need to sanitize anything from the user's info and try to post it in a sane form...maybe upload it in a file to avoid additional escaping issue with github's comment engine.

I don't know SQL yet.  If you want to talk me through the query needed to get that info from the CSM postgresql database, it will speed things up.

**Comment by mew2057** [comment]
Is this example in the json file?

```eval $($LMOD_CMD bash \\"$@\\");\\n [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\\n} BASH_FUNC_```

I'm trying to identify where the characters aren't escaped, I am unable to replicate in our environment at this time.

In logstash is the listening port using the `json` codec? The sample is using:
``` JS 
# Filebeats
beats {
   port => 10523
  codec=>"json"
}
```

**Comment by morrone** [comment]
Correct to both questions.

**Comment by mew2057** [comment]
`psql csmdb -c "SELECT user_flags FROM csm_step_history WHERE step_id=<STEP_ID> AND allocation_id=<ALLOCATION_ID>"`
