### ISSUE TITLE
LLNL: dgemm-gpu in CSM hcdiags now fails on all Sierra/Lassen nodes

### ISSUE THREAD

**Issue by gzjfn4** [IBM/CAST#316]
dgemm-gpu in CSM hcdiags now fails on all Sierra/Lassen nodes, even without hardware issues. We've been able to replicate this on multiple nodes.
 
 Results:
 The Spectrum MPI /opt/ibm/spectrum_mpi/ is used.
 Using /tmp/43336/ as directory for the logs
 GPU: 0
 lassen1: PERFORMANCE FAILURE: 4589 GF/s; EXPECTED PERFORMANCE: 6500 GF/s
 GPU: 1
 lassen1: PERFORMANCE FAILURE: 4819 GF/s; EXPECTED PERFORMANCE: 6500 GF/s
 GPU: 2
 lassen1: PERFORMANCE FAILURE: 5167 GF/s; EXPECTED PERFORMANCE: 6500 GF/s
 GPU: 3
 lassen1: PERFORMANCE FAILURE: 5089 GF/s; EXPECTED PERFORMANCE: 6500 GF/s
 GPU: 0,1,2,3
 lassen1: PERFORMANCE FAILURE: 13796 GF/s; EXPECTED PERFORMANCE: 28884 GF/s
 dgemm-gpu.sh test FAIL, rc=99
 Remote_command_rc = 99

**Comment by sanomiya** [comment]
According to Peter Wong (Spectrum mpi team), the final solution by NVIDIA for the  degraded performance is to add the  "numactl --membind=0,8" in the jsrun command.
This fix will be released in PTF 10, December timeframe.

`$MPI_ROOT/jsm_pmix/bin/jsrun  ...   numactl --membind=0,8 ./dgemm_gpu $MATRIX_DIM...`

**Comment by sanomiya** [comment]
Please, also read the /opt/ibm/spectrum_mpi/healthcheck/dgemm_gpu/README.dgemm_gpu file.
Based on the output above, it looks like EXPECTED_PERF is not set correctly.
