### ISSUE TITLE
Suggestions for improving or correcting CAST online doc

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#322]
**Summary:**
These suggestions are derived from experiences in testing the Big Data Store (BDS) software components on IBM Power Systems. 

**Is your feature request related to a problem? Please describe.**
Suggestions include critical documentation updates that will help users see an important step or pitfall to avoid more issues later. The first suggestion is the requirement to run createIndices.sh to set up cast-allocation data mapping.

**Describe the solution you'd like**
From the current CAST doc, running createIndices.sh is *(optional)* that could be easily missed when the admin setting up many software components for BDS. Not running createIndices.sh results in CSM data being stored into BDS in *wrong* formats.

One obvious example is: The date and time stamp field is stored as text string. Furthermore, all the data fields are pretty much not searchable (through the CSM BDS Use Cases for example) even though they show up fine in kibana indices.

The side effects can be the time consuming and complicate process of cleaning elasticsearch and kibana indices and more.

**Describe alternatives you've considered**
It would be helpful to emphasize in the doc. that the admin needs to run createIndices.sh before starting to collect CSM data into BDS.

Also, the name of the script could be more specific then just createIndices. The script actually creates the cast-allocation index with the data mapping templates provided with CSM BDS. Admin will not miss it if the script is something like "createAllocationIndex".

**Additional context**
CSM BDS software also provides Use Case scripts as examples for how to verify the data and validate the BDS configurations. This is a good idea but some simple guideline or examples may help new users to get started.

Additional suggestion for a short Section in the CAST doc. called something like "Initial Data Verification". Here's a very high level of points or steps to be included in this Section:
• Run a simple job three times to generate cast-allocation data. Take notes on job ID and arguments.
• Bring up kiban GUI and check for Elasticsearch Indices. Check the mapping. Create a kibana index for cast-allocation and check for job data fields.
• Run findJobTimeRange.py to check job start and end time.
• Run findJobsInRange.py with the above times plus some different times.
• Run findUserJobs.py with the user ID of the job and some different IDs.
• Run findJobKeys.py to search a keyword in the jobs' output.
• Run findJobMetrics.py to see elasticsearch metrics aggregation examples.
• Run findWeightedErrors.py for further debugging with helps of data.

**Issue Source:**
Testing of CSM BDS in IBM Integrated System Testing.

**Comment by mew2057** [comment]
Recategorized script in #329, working on making CSM sourced timestamps cleaner and fixing CSM datatypes to not use index mapping.
