### ISSUE TITLE
Difference in elasticsearch @timestamp and times logged in data

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#340]
**Describe the bug**
Some BDS Use Cases require correlating the local times logged in CSM job allocation and other indices with elasticsearch $timestamp (universal).

**To Reproduce**
1. Go to '/opt/ibm/csm/bigdata/python/'
2. Run ./findJobKeys.py -a <aid or jid> -k <keyword>*, where keywords can be found in syslogs.
3. With the right aid and keywords, none of them are found by the script:
```
[root@bd01 python]# findJobKeys.py -a 1430 -k kernel
Got 1 Hit(s) for specified job, searching for keywords.
Got 0 keyword hits:

Keyword | Count
 kernel | 0
```

**Expected behavior**
With the same command as above, the command should "hit" those keywords and print out the counts.

**Screenshots**
```
[root@bd01 python]# old/findJobKeys.py -a 1430 -k kernel
Got 1 Hit(s) for specified job, searching for keywords.
Got 672 keyword hits:

Keyword | Count
 kernel | 672
```

**Environment (please complete the following information):**
 - Machine bd01, bd02 (IST)
 - Version CSM 1.3.0-1296

**Additional context**
Other Use Case scripts with similar issue:
- findJobMetrics.py
- findJobWeightedErrors.py

**Issue Source:**
Need to get those BDS Use Cases to work.

**Comment by thanh-lam** [comment]
Upgraded csm-bds on one of the BDS servers to a later nightly build level, 1312, for testing purposes. 
```[root@bd02 python]# rpm -qa | grep csm
ibm-csm-bds-1.3.0-1312.noarch```

From a quick test, findJobKeys.py does work as following:

```[root@bd02 python]# ./findJobKeys.py -j 107
Got 1 Hit(s) for specified job, searching for keywords.
Got 38 keyword hits:

Keyword | Count
     .* | 38```

By looking into all the 38 messages found with option -v, found these keywords that findJobKeys.py also found:
```[root@bd02 python]# ./findJobKeys.py -j 107 -k "pam_unix" "Disconnected"
Got 1 Hit(s) for specified job, searching for keywords.
Got 8 keyword hits:

     Keyword | Count
    pam_unix | 4
Disconnected | 4```

With -v option:
```Displaying 8 of 8 logs:
2018-10-17T17:54:48.366203-04:00 f10n15 | pam_unix(sshd:session): session opened for user protocol by (uid=0)
2018-10-17T17:54:48.426823-04:00 f10n15 | Disconnected from 172.16.5.3 port 33526
2018-10-17T17:54:48.426633-04:00 f10n15 | Received disconnect from 172.16.5.3 port 33526:11: disconnected by user
2018-10-17T17:54:48.427673-04:00 f10n15 | pam_unix(sshd:session): session closed for user protocol
2018-10-17T17:54:48.459085-04:00 f10n16 | pam_unix(sshd:session): session opened for user protocol by (uid=0)
2018-10-17T17:54:48.525095-04:00 f10n16 | Received disconnect from 172.16.5.3 port 38790:11: disconnected by user
2018-10-17T17:54:48.525253-04:00 f10n16 | Disconnected from 172.16.5.3 port 38790
2018-10-17T17:54:48.526108-04:00 f10n16 | pam_unix(sshd:session): session closed for user protocol```

**Comment by mew2057** [comment]
This requires a fix in how CSM generates timestamps. I'm moving this to 1.5.0 with other BDS defects.

**Comment by thanh-lam** [comment]
Okay for moving to 1.5. It needs to work especially with findJobMetrics.py. I've not been able to get it to display any metrics related to a job. findJobKeys.py and findJobWeightedErrors.py are working to some extent.

**Comment by mew2057** [comment]
I'm dropping it back to 1.4.0 due to client request I should be able to devise a solution in the next 48 hours.

**Comment by mew2057** [comment]
Kibana should translate UTC to Local time, so it shouldn't be an issue.

**Comment by thanh-lam** [comment]
Okay, how about those bigdata python scripts like `findJobMetrics.py`? Anything needs to be done there for the time differences?

**Comment by thanh-lam** [comment]
Lowering sev. to 4 to keep this timestamps formatting in mind. We will have some chances to revisit the BDS use case scripts again.

**Comment by thanh-lam** [comment]
Closing this issue because I was able to get `findWeightedError.py` to work with at least on allocation:
```
# ./findWeightedErrors.py -a 290 -H csm03,f4n05 --errormap WeightedErrorMap.json
 
"CSM RAS" Max Score : 1006.3311
"CSM RAS" Count : 34
  "msg_id | .*" : 34
==========================================
 
"Syslog Errors" Max Score : None
"Syslog Errors" Count : 0
  "message | error" : 0
  "message | kdump" : 0
  "message | xid" : 0
==========================================
 
"SSD_WEAR" Max Score : None
"SSD_WEAR" Count : 0
  "wear_total_bytes_read | .*" : 0
==========================================
 
"Cast Counters" Max Score : None
"Cast Counters" Count : 0
  "data.mem_active | 12000000" : 0
  "data.cpu_system | 10" : 0
==========================================
```
Also, `findJobMetrics.py` worked with certain index and field as following example:
```
# ./findJobMetrics.py -a 600 -H f4n05 -i "cast-log-syslog*" -f port
Got 1 Hit(s) for specified job:

Metric Analysis for Allocation ID 600 :

     Field |            Min |            Max |        Average |        Std Dev | Count
      port |      40628.000 |      40628.000 |      40628.000 |          0.000 | 86
```
Although, using the field `port` doesn't make lots of sense, it showed the metric worked. Why `port` is a `metric` is a different question. I've tried many other fields that are better candidates for metric fields but `findJobMetrics.py` didn't find metric about those fields.
