### ISSUE TITLE
RPM packaging of python modules required

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#348]
PR #332 introduced a python script called "csm_db_history_archive.py", which is a key component of the csmdb to bds archiving process.  According to the PR:

"The new implementation requires psycopg2 which may be installed using pip: pip install psycopg2"

pip will not be an adequate delivery method.

We require that the psycopg2 module be rpm packaged, and the package that contains the csm_db_history_archive.py script must have a Requires for the psycopg2 package.

Likewise, the "use cases" python scripts depend on the "elasticsearch" python module.  This too needs to be rpm packaged, and the correct Requires need to be added to the rpm that contains the python use case scripts.

It would be very nice to also rpm package the "elasticsearch_dsl" module at the same time.

**Comment by mew2057** [comment]
`psycopg2` is already bundled with red hat. This rpm may be used in lieu of pip.

I need to look into the `elasticsearch` modules.

**Comment by morrone** [comment]
Do we have an rpm dependency on psycopg2 in the mean time?

**Comment by pdlun92** [comment]
Still looks like we are missing the dependency
```
[root@c650mnp05 rpms]# rpm -qR ibm-csm-db-1.4.0-1756.noarch
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
/bin/bash
/bin//bash
/bin/python
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by pdlun92** [comment]
Also, looks like there is a `python-elasticsearch` package in epel
```

**Comment by mattaezell** [comment]
FYI @miidon
