### ISSUE TITLE
zimonCollector.py displays strange message "QueryHander: found ."

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#364]
**Describe the bug**
When run the script `/opt/ibm/csm/bigdata/data-aggregators/zimonCollector.py, it displayed strange message. And, `cast-zimon-*` index from kibana stopped showing new data after 10/17.

**To Reproduce**
1. Go to `/opt/ibm/csm/bigdata/data-aggregators`
2. Run command `./zimonCollector.py`
3. See error
```
[root@f4n07 data-aggregators]# ./zimonCollector.py
2018-10-24 16:54:02,440 QueryHandler.__do_query +427: DEBUG    [50965] QueryHandler: found .
 through receiving chunks
```

**Expected behavior**
Every time that command is run, it should generate zimon data that is sent to elasticsearch index `cast-zimon-*`. The same command is also put in the node's crontab to run every 10 minutes. Used to see data in kibana before 10/17, which was the time of a new upgrade to csm 1.3.0 1391.

**Screenshots**

**Environment (please complete the following information):**
 - Machine f4n05, f4n07 (IST)
 - Version CSM 1.3.0 1401

**Additional context**
The message displayed by the command should also be pointing out what's wrong.

**Issue Source:**
Used to see `cast-zimon-*` data in kibana before 10/17, which was the time of a new upgrade to csm 1.3.0 1391.

**Comment by mew2057** [comment]
This is the `QueryHandler` library having a debug level logging command, CAST is not responsible for this output. The only way to fix this is to increase `level=logging.DEBUG` to `level=logging.INFO`.

**Comment by mew2057** [comment]
The zimon collector ships directly to logstash as a JSON object now, that pattern is a legacy pattern.

**Comment by thanh-lam** [comment]
How do we check to see if the JSON objects are received by logstash? And, how about from logstash to elasticsearch? Any changes in `/opt/IBM/zimon/ZIMonCollector.cfg`? I have the `peers` setting in both Service Nodes as following:
```
...
peers = {
        host = "f4n05-ib0"
        port = "9085"
}, {
        host = "f4n07-ib0"
        port = "9085"
}
...
```

**Comment by thanh-lam** [comment]
Found lots of these messages in `/var/log/zimon/ZIMonCollector.log`
```
...
Oct-25 16:50:01  [Warning] QueryEngine: searchForMetric: could not find metaKey for given metric gpfs_ns_bytes_read, returning.
Oct-25 16:50:01  [Warning] QueryEngine: searchForMetric: could not find metaKey for given metric gpfs_ns_bytes_written, returning.
Oct-25 16:50:01  [Warning] QueryEngine: searchForMetric: could not find metaKey for given metric gpfs_ns_tot_queue_wait_rd, returning.
Oct-25 16:50:01  [Warning] QueryEngine: searchForMetric: could not find metaKey for given metric gpfs_ns_tot_queue_wait_wr, returning.
Oct-25 16:53:30  [Info   ] Collector: timerEvent called, number of entries in prevLog: 0, in currLog: 143
...
```

**Comment by thanh-lam** [comment]
With some help from Fernando, found out that the kibana index has been changed from "cast-zimon-*" to "cast-counters-*". I've been getting data from this index. However, some fields are "undefined" or "questionable" in kibana. They had the "null" value. They should be set to 0 if there's no data collected.
```
    "data": {
      "cpu_system": 0.004,
      "mem_active": 5090647,
      "cpu_user": 0.002,
      "gpfs_ns_bytes_written": null,
      "gpfs_ns_bytes_read": null,
      "gpfs_ns_tot_queue_wait_rd": null,
      "gpfs_ns_tot_queue_wait_wr": null
    },
```

**Comment by thanh-lam** [comment]
Just a note on the timestamp that might have been a problem for searching:
```
...
    "source": "f4n05",
    "@version": "1",
    "@timestamp": "2018-10-29T21:20:01.653Z",
    **"timestamp": 1540847520**
  },
  "fields": {
    "@timestamp": [
      "2018-10-29T21:20:01.653Z"
    ]
  }
```

**Comment by thanh-lam** [comment]
Verified with CSM 1.4.0-1756. Those data fields are now set to 0. Closing.

"data": {
    "gpfs_ns_tot_queue_wait_rd": 0,
    "gpfs_ns_tot_queue_wait_wr": 0,
    "gpfs_ns_bytes_read":0,
    ...
    "gpfs_ns_byte_written": 0
}
