### ISSUE TITLE
findWeightedErrors produces error output when error map contains indexes that don't exist

### ISSUE THREAD

**Issue by pdlun92** [IBM/CAST#377]
**Describe the bug**
If the `errormap` file passed as an arg to `findWeightedErrors.py` contains any indexes that don't exist, the use case will incorrectly produce error output

**To Reproduce**

1. create an `errormap` file that lists indexes that don't exist
2. run `findWeightedErrors.py` use case

**Observed Output**
```
[root@c650f04p39 python]# ./findWeightedErrors.py -a 1002 --errormap sampleWeightedErrorMap.json

"Syslog Errors" Max Score : 63.14231
"Syslog Errors" Count : 1
  "message | xid" : 1
  "message | error" : 0
  "message | kdump" : 0
==========================================

"Zimon Counters" Max Score : 0.0
"Zimon Counters" Count : 0
Traceback (most recent call last):
  File "./findWeightedErrors.py", line 258, in <module>
    sys.exit(main(sys.argv))
  File "./findWeightedErrors.py", line 242, in main
    for (aggregation,value) in sorted(aggregations.iteritems(),
AttributeError: 'list' object has no attribute 'iteritems'
```
In this case I believe the Zimon index is creating the error. Note this is using the shipped `sampleWeightedErrorMap.json` file

**Comment by mew2057** [comment]
Fix has been implemented, moving to verify.
