### ISSUE TITLE
Support the  Spectrum MPI  healthcheck PTF10

### ISSUE THREAD

**Issue by sanomiya** [IBM/CAST#381]
With PTF10, Spectrum MPI healthcheck  directory structure is:
```/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]```
```
/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]/daxpy
/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]/dgemm
/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]/dgemm_gpu
/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]/jlink
/opt/ibm/spectrum_mpi/healthcheck/POWER[8|9]/mpirun_scripts
```

Prior to PTF10, the directory structure is:
```/opt/ibm/spectrum_mpi/healthcheck```
```
/opt/ibm/spectrum_mpi/healthcheck/daxpy
/opt/ibm/spectrum_mpi/healthcheck/dgemm
/opt/ibm/spectrum_mpi/healthcheck/dgemm_gpu
/opt/ibm/spectrum_mpi/healthcheck/jlink
/opt/ibm/spectrum_mpi/healthcheck/mpirun_scripts
```

**Comment by Obihoernchen** [comment]
Why did you delete `[-m]  Use mpirun instead of jsrun`?
I use it :-O

**Comment by sanomiya** [comment]
@Obihoernchen For daxpy?

**Comment by sanomiya** [comment]
daxpy can run without mpirun or jsrun, as a simple local program. No need of [-m] option. Let me know if by mistake I removed [-m] from the other tests.

**Comment by Obihoernchen** [comment]
@sanomiya oh yes you are totally right! I didn't read daxpy...
My bad. Sorry.
