### ISSUE TITLE
libcsmpam.so still printing text during 'session' module usage which it should never do

### ISSUE THREAD

**Issue by adambertsch** [IBM/CAST#452]
**Describe the bug**
printing text to stdout/stderr from session breaks rsh.  it should not be done.

**To Reproduce**
[bertsch2@butte5 ~]$ rsh e9
[csmapi][warning]	/home/ppsbld/workspace/PUBLIC_CAST_V1.2.x_ppc64LE_RH7.5_ProdBuild/csmi/src/common/src/csmi_common_utils.c-147: the Error Flag Set
[csmapi][error]	csmi_sendrecv_cmd failed: 36 - csm_cgroup_login[325976642]; User not authorized.

**Expected behavior**
No text should ever be printed during 'session' use, as it breaks rsh.  We are already returning PAM_SUCCESS in session as we expect (we can return failures in account, which we do, I believe)

**Environment (please complete the following information):**
CSM 1.2.1 (and up?)  -- still need to verify on later versions, but am not aware of any changes addressing this since 1.2.1
edit: confirmed in 1.3.0

**Comment by mew2057** [comment]
This is an issue with the infrastructure connection code itself when receiving errors. There should be a mechanism to disable this (although it's in the API). I'll take a look at this soon.

**Comment by adambertsch** [comment]
A 'quiet' flag that suppresses all printed errors (but not file logged errors) would be fine for our use as well.

**Comment by mew2057** [comment]
Adding the following line, should disable all printed errors:

``csmutil_logging_level_set("off");``
