### ISSUE TITLE
Collect and store LV read and write counts

### ISSUE THREAD

**Issue by mattaezell** [IBM/CAST#469]
The BB software and the CSM BB LV APIs currently support a count of the bytes written and bytes read.  It would be useful to also include the count of reads and writes.  This would allow us to calculate average I/O size, so we can (try to) understand if people are using these devices for checkpoints (large, streaming writes followed by large reads), memory extension (many small reads and writes), ML/DL workloads (large reads to load in a dataset followed by many small, random read IOs), or something else.

**Comment by NickyDaB** [comment]
## Recap: 
Current fields in the `csm_lv_history` table, which are related to this conversation: 
- num_bytes_read
- num_bytes_written

These only include the total number of bytes. good information, but not the full story. It would be nice to know how many times something was read. 

Example: if the `num_bytes_read` was `1000`. Was that 1 byte read 1000 times or 1000 bytes read once? In the current system, we do not know.

## Proposed updates:
- num_bytes_read
- num_bytes_written
- num_reads
- num_writes

## ToDo: 
- [ ] @williammorrison2: Include 2 new fields: `num_reads` and `num_writes`. 
**Reason:** To include the missing parts of the picture noted above. Now we can tell if those 1000 bytes above were 1 byte written 1000 times or 1000 bytes written once. 

## Questions: 
These are proposed updates from a CSM perspective with our current information. But during brainstorming we thought of some more questions:
@tgooding , you looked into this. So I direct this question to you. 

1. Are these fields only available after an LV is completed? 
If so we will only include these fields in our history table. 
2. Are these fields available for capture at any point during a LV's life? If so we can add them into the live table. This will provide a current snapshot of LV information should this data be updated and given to CSM throughout an allocation's life. 
3. Would BurstBuffer call LV update during the life of an allocation and update these fields, if CSM did place them in the live table? 

@mattaezell, you requested this feature, so I direct the following question to you:

1. If the above is possible, CSM kept track of the live data, and BB updated the live data, would that be something that would be valuable for you? 
2. Would you want to be able to see the number of read and writes during a live lv, or is this something that you don't see a need for and only expect to use these fields after an LV has been deleted?

**Comment by mattaezell** [comment]
Hello @NickyDaB 

All 4 of these fields (count/sum of reads/writes) can be read (and are updated by the kernel) live during the job.

While the concept of "top" for the entire cluster might be interesting, it's not what I was originally requesting.  What all data fields (outside of LV) are updated live?  Separate from CSM, we are looking into a statistics collector that would record periodic samples.

**Comment by NickyDaB** [comment]
@mattaezell 

> What all data fields (outside of LV) are updated live? 

I'll have to ask around on the team for everything outside of LV, but for now I can say that inside LV, "current size" is something that CSM can keep track of live.  @fpizzano  has better knowledge of CSM as a whole. He can answer your question. 

But as a note for LVs, CSM doesn't directly monitor updates to these type of metrics.  Someone uses our APIs to tell us that it has been updated, then we do some math checks to make sure that the math on these numbers seems legit. More of a check to make sure everyone is playing nice. CSM doesn't control the LVs. We just keep track of whatever information is told to us.  

So in practice, if someone is using and calling `csm_bb_lv_update` and giving us new information as the job runs, we keep track of current size, but if someone only calls lv create then lv delete, we won't have the granularity of the intermediate data. (in regards to the current size field)

**Comment by NickyDaB** [comment]
> All 4 of these fields (count/sum of reads/writes) can be read (and are updated by the kernel) live during the job.

I'll discuss with @fpizzano and @williammorrison2  if this is something CSM should keep track of live. As right now, sum of reads/writes is only updated at the end, and only in history.

**Comment by NickyDaB** [comment]
@williammorrison2 has updated the database to include these 2 new fields in the lv history table.  

the new api changes for csm_bb_lv_delete - adding in the 2 new fields are optional and implemented as we discussed. if the field is not supplied then they will be inserted into the database as null. these changes are up on the master branch. they will be available in csm 1.5 

@mattaezell -  @fpizzano  is wondering how you will be using this data. There is not currently a csm api to query information from the lv history table. will you be grabbing it from some other way?

**Comment by mattaezell** [comment]
Right now, I'm querying the database directly (I'm aware this is subject to break, as the schema is not a contract) using a query like:
```
SELECT
	a.primary_job_id as jobid,
	a.allocation_id as allocid,
	a.user_name as user,
	round(l.sum_read_bytes/1024/1024/1024::numeric,2) as sum_r_GiB,
	round(l.sum_write_bytes/1024/1024/1024::numeric,2) as sum_w_GiB,
	l.num_nodes as reported_nodes,
	a.num_nodes as alloc_nodes,
	round(l.max_read_bytes/1024/1024::numeric,2) as max_r_MiB,
	round(l.max_write_bytes/1024/1024::numeric,2) as max_w_MiB
FROM
	(SELECT 
		allocation_id,
		sum(num_bytes_read) as sum_read_bytes,
		sum(num_bytes_written) as sum_write_bytes,
		count(*) as num_nodes,
		max(num_bytes_read) as max_read_bytes,
		max(num_bytes_written) as max_write_bytes
	FROM
		csm_lv_history
	WHERE
		begin_time >= '2019-01-01'
	GROUP BY
		allocation_id 
	ORDER BY
		allocation_id desc 
	) l
JOIN
	csm_allocation_history a
ON 
	l.allocation_id = a.allocation_id
ORDER BY
	max_w_MiB desc
LIMIT
	10;
```

**Comment by besawn** [comment]
@mattaezell I think the features requested in this issue were delivered as part of CSM 1.5.0. Is there anything else needed for this item or can this issue be closed now? Thanks!

**Comment by mattaezell** [comment]
> @mattaezell I think the features requested in this issue were delivered as part of CSM 1.5.0. Is there anything else needed for this item or can this issue be closed now? Thanks!

Yes, thanks!
