### ISSUE TITLE
csm logstash/kibana rpm package scriptlets are broken

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#472]
The scriptlets in the rpm packages ibm-csm-bds-logstash and ibm-csm-bds-kibana are broken.

The problem is one of ordering during rpm upgrades .  The postuninstall scriptlet of the _old_ package is the last scriptlet to run.  That scriptlet unconditionally removes the plugin.  So the plugins will never be functional after an upgrade.

See the section "The lowdown on upgrades" in this article for a more detailed explanation of the issue, and how to fix it:

https://www.ibm.com/developerworks/library/l-rpm2/index.html

Secondly, I had previously mentioned that you should not have the "if [ -f /usr/share/kibana/bin/kibana-plugin ]" conditionals in the scripts at all.  We do _not_ want the rpm to ever silently fail to install correctly.  Please remove those when you fix the primary issue.

**Comment by mew2057** [comment]
Fix is now pending.

**Comment by morrone** [comment]
Commit eb84b64 looks like good cleanup, but it does not appear to address the fundamental problem from this ticket.

The basic problem is this:

As of eb84b64, the .pre.uninstall script of the packages will unconditionally remove the plugin.  This is a bug.  When doing an rpm upgrade, the .pre.uninstall of the OLD package runs _after_ the .post.install of the NEW package.  So we will _always_ wind up with the plugin in an uninstalled state after an rpm upgrade.

You need to check the first argument to the script.  That argument will tell you:

> If the first argument to %pre is 1, the RPM operation is an initial installation. If the argument to %pre is 2, the operation is an upgrade from an existing version to a new one.
> Similarly, the arguments to a %post are 1 and 2 for a new installation and upgrade, respectively. (Again, %pre and %post aren't executed during an uninstallation.)
> If the first argument to %preun and %postun is 1, the action is an upgrade.
> If the first argument to %preun and %postun is 0, the action is uninstallation.

This is all explained in the link that I provided at the top of this ticket.

**Comment by mew2057** [comment]
I see now, I've pushed a fix to the PR. I also added some echos to track the scriptlet actions.
