### ISSUE TITLE
csm_allocation_query_details should print all fields

### ISSUE THREAD

**Issue by mattaezell** [IBM/CAST#473]
csmi/src/wm/cmd/allocation_query_details.c line 156
```
                        if( ad->node_accounting[i]->gpfs_read > 0 )
                            printf("   gpfs_read:                   %"PRId64 "\n",
                                ad->node_accounting[i]->gpfs_read);
```

csm_allocation_query_details skips values that are zero.  I think it would be better to print all the keys/values, even if zero, for consistency.

**Comment by mew2057** [comment]
Change has been merged.
