### ISSUE TITLE
csm_transaction.log is too large

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#507]
Our csm_transaction.log on sierra has grown unwieldy at over 36GB in size, and over 5.5million lines.

We need a mechanism to rotate and delete old copies of this log (and others like it) once the data is safe in elasticsearch.

**Comment by mew2057** [comment]
Hi, there should be a rollover mechanism in place today. On the Master Daemon Config file (`/etc/ibm/csm/csm_master.cfg`) modify the `transaction_rotation_size`.

@besawn I mirrored the logging rollover for the standard daemon is there anything you can add on this?

**Comment by thanh-lam** [comment]
Our CSM 1.4.0-1756 has `csm_master.cfg` with "transaction_rotation_size" = 1G. But, I can't tell if it works because the `csm_transaction.log` is not reaching 1G yet. That setting is in the sample `csm_master.cfg` by default, at `/opt/ibm/csm/share/etc/`.

**Comment by mew2057** [comment]
@morrone can you give us your `allocation_metrics_rotation_size` and `transaction_rotation_size` in the `/etc/ibm/csm/csm_master.cfg`.

**Comment by morrone** [comment]
It looks like we have all of these three settings in the "log" area:

```
            "rotationSize"                      : 1000000000,
            "transaction_rotation_size"         : 1000000000,
            "allocation_metrics_rotation_size"  : 1000000000
```

**Comment by morrone** [comment]
So just to be clear, it does not appear that the rotation is working.

**Comment by thanh-lam** [comment]
Agree. It's not working on ours either. I verified it by setting the size to 1000000. And, now `csm_transaction.log` has grown to 166000+. Unless, that setting value means something else.

```
# grep rotation /etc/ibm/csm/csm_master.cfg
            "#rotationSize_comment_1"           :   "Maximum size (in bytes) of the log file, 1000000000 bytes is ~1GB",
            "rotationSize"                      :   1000000000,
            "#transaction_rotation_comment"     :   "Testing on small cluster, default size 1000000000",
            "transaction_rotation_size"         :   1000000,
            "allocation_metrics_rotation_size"  :   1000000

# ls -l csm_transaction.log
-rw-r--r-- 1 root root 1663823 Jan 17 22:28 csm_transaction.log
```

**Comment by mew2057** [comment]
Did some digging, might have a fix ready later toady.

**Comment by mew2057** [comment]
I have a fix ready now, it requires that filebeats change the pattern match for the transaction and metrics logs. PR is pending.

**Comment by morrone** [comment]
Great!

Will the oldest rotated out files be automatically removed?

**Comment by mew2057** [comment]
I'm working on leveraging Filebeats to clear the rotation now. I want to drive cleanup from the Consumer, as Producer driven cleanup might result in data loss.
