### ISSUE TITLE
stagein: request to refresh /opt/ibm/bb/scripts/stagein_user.pl

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#508]
**Describe the bug**
The example user stage in script has some apparent stale lines as the BB software has changed over time.

 - one must add the following ```use lib ‘/opt/ibm/bb/scripts’;``` or otherwise, one must be sure that this path in is the default PERL search path $PERL5LIB, in which case adding a comment around the use line would be helpful
 - LAST_NODE is no longer defined in bbtools.pm, perhaps the solution is to define that in the example stage in script as ```$LAST_NODE = scalar(@HOSTLIST_ARRAY) - 1;```
 - In the bbcmd to copy files, one must change ```--handle=$result->{'0'}{'transferHandle'}``` to ```--handle=$result->{'0'}{'out'}{'transferHandle'}```
 - the script writes its filelist to a temporary file in /tmp.  However, that path is unlikely to be readable from a compute host, so perhaps change this to use a path on the parallel file system instead

**Expected behavior**
This example is very useful to serve as a starting point when creating a new user stage script.  I would like to keep it around, and have it updated so that it works using the current BB software.

**Environment (please complete the following information):**
 - rpm: ibm-burstbuffer-1.4.0-1756.ppc64le

**Comment by tgooding** [comment]
Thanks - - commit da096200d690086de693d4c68b03c394449f589e should resolve.

**Comment by adammoody** [comment]
Great.  Thanks, @tgooding !

**Comment by tgooding** [comment]
Stale issue, closing.  Reopen if its not complete.
