### ISSUE TITLE
stagein: request for job's current working directory and jobid in user prestage script

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#509]
**Summary:**
It would be helpful to obtain certain environment information for a job from within the user prestage and poststage scripts.  In particular, it would be useful to have the job id and the job's current working directory.

Writing and debugging new prestage / poststage scripts is non-trivial.  A likely use case will be for system support staff to create common scripts that are installed in global directories that all users can invoke.  This would amount to an option that the user can cut-and-paste into their bsub command, e.g.,

```bsub -stage 'in=/system/path/to/global/stagein.pl'```

These stage scripts then would be programmed to look for well-defined file names in the job's working directory, whose content would be a simple text file that lists the set of files to be staged for example.  The idea being that is much simpler for an end user to create such a text file than to modify and debug stage scripts.

For that to work, the stage in script would need to know the job's current working dir.

Additionally, it would be useful to know the job id to avoid file name collisions with other jobs in case the stage script needs to generate any king of logging output to be written back for the user.

**Describe alternatives you've considered**
An alternative that likely works in the current software is for the user to explicitly set an environment variable pointing to the directory or file list that the script should use.  However, that is error prone as the user could make typos or simply forget this step.  Even then, the stage script could detect and report an error message.  The downside is that it requires two commands to submit each job, rather than one.

**Comment by tgooding** [comment]
Force close, reopen if this is not working.
