### ISSUE TITLE
CSM rpms dependencies 

### ISSUE THREAD

**Issue by fpizzano** [IBM/CAST#514]
Some of the CSM rpms do not pull the complete dependencies list or rpms, for example:

```
# cd /opt/ibm/csm/tools
# python API_Statistics.py -h
Traceback (most recent call last):
  File "API_Statistics.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
# rpm -qa | grep ibm-csm
ibm-csm-hcdiag-1.4.0-1756.noarch
ibm-csm-api-1.4.0-1756.ppc64le
ibm-csm-db-1.4.0-1756.noarch
ibm-csm-bds-1.4.0-1756.noarch
ibm-csm-core-1.4.0-1756.ppc64le
# rpm -qa | grep -i numpy
#
```

**Comment by mew2057** [comment]
There might be more situations like this, numpy had a requirement dependency in the old bds code. The only question I have is does this belong in `csm-core`? If we add the requirement it will force numpy to be installed on every node in the cluster.

**Comment by mew2057** [comment]
This also indicates a set of test cases that need to be written for CI.

**Comment by besawn** [comment]
If API_Statistics.py is not needed on every node in the cluster, I would suggest we should consider repackaging it into a different rpm to prevent unnecessary packages from being installed everywhere, as John mentioned above.

Possible suggestions: move API_Statistics.py to the existing unittest rpm or create a new tools rpm.
