### ISSUE TITLE
bbcmd cancel segfault

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#528]
**Describe the bug**
When running inside of an interactive allocation and trying to cancel an ongoing transfer with multiple contributors, I got the following segfault:

```
bbcmd cancel --target=0- --jobstepid=2 --handle=1567724507
Segmentation fault (core dumped)
```

In this job, 250 hosts completed, and 6 were stuck INPROGRESS.

**Environment (please complete the following information):**
ibm-burstbuffer-tools-1.4.0-1756.ppc64le
ibm-burstbuffer-1.4.1-1774.ppc64le
ibm-burstbuffer-mn-1.4.0-1756.ppc64le
ibm-burstbuffer-tests-1.4.0-1756.ppc64le
ibm-burstbuffer-lsf-1.4.1-1774.ppc64le

**Comment by adammoody** [comment]
Passed the core file along to @tgooding

**Comment by tgooding** [comment]
There were fixes to bbcmd / nodecontroller_csm.cc that addressed negative/NULL responses to csm_bb_cmd().  Its possible those fixes addressed this cancel crasher.  Also, I don't think we've seen this recently.  Setting to verify.

**Comment by tgooding** [comment]
Stale issue, closing - - reopen if this reoccurs.
