### ISSUE TITLE
Metric timestamps use labeling that clashes with special Logstash fields

### ISSUE THREAD

**Issue by chrismuzyn** [IBM/CAST#530]
**Describe the bug**
Metrics that appear in the default csm_allocation_metrics.log file come with the timestamp field `"@timestamp".`  The `@timestamp` field is replaced immediately upon ingestion by logstash.

**To Reproduce**
1. Ingest a log from the csm_allocation_metrics.log file.
2. Let the log propagate into logstash.
3. Use the ruby debug output to see that `@timestamp` has been replaced by the time the log was ingested into logstash.

**Expected behavior**
`@timestamp` should be replaced by another label so the metric collection time can be preserved.

**Environment (please complete the following information):**
 - Filebeats, Elasticsearch, and Logstash 6.3.2.

**Comment by mew2057** [comment]
Change merged, `@timstamp` is now `timestamp`

**Comment by chrismuzyn** [comment]
It looks like a similar thing is happening with the "source" field, but this time filebeats is overwriting it.  Should I open a new issue or can I piggyback on this one?

**Comment by mew2057** [comment]
We have this on Issue #535.

**Comment by chrismuzyn** [comment]
Oh awesome, thank you!
