### ISSUE TITLE
CSM jitter mitigation setting for IRQ Affinity does not work

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#572]
**Describe the bug**
In CSM 1.5, csm_compute.cfg can contain the Jitter Mitigation block to define these attributes, which are shown default settings:
```
        "jitter_mitigation" :
        {
            "system_smt"         : 0,
            "irq_affinity"       : false,
            "core_isolation_max" : 4,
            "socket_order"       : "00"
        },
```
When `irq_affinity` was set to `true`, we expected CSM to set the IRQ registers accordingly and stop `irqbalance`. We checked and found `irqbalance` was not stopped, as it has been running since Jan 22nd.
```
root       5233      1  0 Jan22 ?        01:29:44 /usr/sbin/irqbalance --foreground
```

And, the irq `smp_affinity` register contents in all levels under /proc/irq/*/ was not set correctly. Neither was in `default_smp_affinity`. The register contents kept changing.

**To Reproduce**
1. Go to `/etc/ibm/csm/` on each compute node.
2. Edit the file csm_compute.cfg and set the `irq_affinity` attribute to true.
3. Restart csmd-compute.service
4. Run `csm_node_attributes_update` to put the node back to `IN_SERVICE`

**Expected behavior**
The irqbalance service should in stop state. And, the IRQ register file smp_affinity and default_smp_affinity should be set accordingly. This shouldn't change until csm cfg is changed.

**Environment (please complete the following information):**
 - Machine f10n15 f10n16
 - Version CSM 1.5.0

**Issue Source:**
IST CSM tests for Jitter Mitigation settings verification.

**Comment by mew2057** [comment]
Additionally what was the core isolation in the allocation create, 0 should not re-balance IRQ affinities. There is a known issue on master where irq is not set properly per handler, but PR #571 is a candidate fix for this bug.

**Comment by thanh-lam** [comment]
Do you mean the core isolation that's passed as an option to the job? I did that with #BSUB -core_isolation 1. And ran a long running job. Here's what in /proc/irq/:
```
# cat default_smp_affinity
ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
# cat */smp_affinity
00000000,00000000,00000000,00000001,00000000
00000000,00000000,00000000,00000000,00000800
00000000,00000000,00000001,00000000,00000000
...
```
**Observation**: default_smp_affinity should be set to F just the first core on both sockets right? Setting to all F doesn't seem to be right, at least for the job duration. And, the IRQ contents of all other registers were all over places. Should they all be set to the same as default_smp_affinity?

**Comment by thanh-lam** [comment]
Verified with CSM 1.5.0-2115 with irq_affinity enable in csm_compute.cfg:
```
        "jitter_mitigation" :
        {
            "system_smt"         : 0,
            "irq_affinity"       : true,
            "core_isolation_max" : 4,
            "socket_order"       : "00"
        },
```
Then, each job was submitted with `#BSUB -core_isolation <number>`, where number was set to 0, 1, 2, 3, 4, 5, and 6 respectively. Each job resulted in `/proc/irq/default_smp_affinity` and `/proc/irq/*/smp_affinity` set correctly.
* `#BSUB -core_isolation 0` - no IRQ balancing
* `#BSUB -core_isolation 1` - default and other smp_affinity registers was set to
      `00000000,00000000,000f0000,00000000,0000000f`
* `#BSUB -core_isolation 2` - default and other smp_affinity registers was set to
      `00000000,00000000,00ff0000,00000000,000000ff`
* `#BSUB -core_isolation 3` - default and other smp_affinity registers was set to
      `00000000,00000000,0fff0000,00000000,00000fff`
* `#BSUB -core_isolation 4` - default and other smp_affinity registers was set to
      `00000000,00000000,ffff0000,00000000,0000ffff`
* `#BSUB -core_isolation 5` - default and other smp_affinity registers was set to
      `00000000,00000000,ffff0000,00000000,0000ffff`
* `#BSUB -core_isolation 6` - default and other smp_affinity registers was set to
      `00000000,00000000,ffff0000,00000000,0000ffff`

Note that, -core_isolation 4, 5, 6 had the same result because `core_isolation_max: 4`.
Also, exceptions found with five registers that can't be changed (by CSM):
```
# grep "ffffffff" /proc/irq/*/smp_affinity
/proc/irq/16/smp_affinity:ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
/proc/irq/17/smp_affinity:ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
/proc/irq/18/smp_affinity:ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
/proc/irq/19/smp_affinity:ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
/proc/irq/63/smp_affinity:ffffffff,ffffffff,ffffffff,ffffffff,ffffffff
```

**Comment by thanh-lam** [comment]
I'm also testing with `socket_order` set to 01, 10, 11.

**Comment by thanh-lam** [comment]
Closing issue after checking IRQ affinity with latest CSM 1.5 build on IST alternate cluster.
