### ISSUE TITLE
CSM allocation create took 3+ minutes on RHEL 7.6 nodes

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#575]
**Describe the bug**
After installing latest CSM 1.5 update, we checked by running simple LSF jobs such as jlink or barrier. Noticed jobs took long time to start and sometimes timed out. That led us into doing lots of further debugging and investigation with CSM allocation create on different node environments. For example:
* P9 water cooled or air cooled
* DD2.1 or DD2.2
* RHEL 7.5 or 7.6

**To Reproduce**
Simple recreation of issue is to run a simple LSF job and monitor allocation create time. However, to do problem isolation and trouble shooting, run csm_allocation_create on each node and record the time.
1. Log in as root to a node that's in question.
2. Run `time /opt/ibm/csm/bin/csm_allocation_create -j 1 -n <node>`
3. Note the time as following:
```
real    1m18.268s
user    0m0.000s
sys     0m0.010s
```
4. Try the same steps on another node and compare.

**Expected behavior**
In normal conditions, the allocation create command takes about 20-30 seconds.

**Environment (please complete the following information):**
 - Machine in istCORAL cluster
 - Version CSM 1.5.0-2065

**Additional context**
This timing issue is not occurring on all nodes in the cluster. It might be just a small number of nodes that caused the long allocation creation time. We have to check many environment variables as mentioned. Will continue to update this issue.

**Issue Source:**
Need to update IST main cluster to CSM 1.5 for testing.

**Comment by thanh-lam** [comment]
Further testing on RHEL 7.6 nodes this morning showed that `csm_allocation_create` took pretty persistent amount of time for more than 3 minutes:
```
# grep 1303405849 csm_master.log
2019-02-18 12:34:10.813991     csmapi::info     | [1303405849]; csm_allocation_create start
2019-02-18 12:34:10.814070     csmapi::info     | [1303405849]; Primary Job Id: 23736; Secondary Job Id: 0; Message: Requesting allocation in database; 
2019-02-18 12:34:10.850547     csmapi::info     | [1303405849]; Allocation ID: 7468; Primary Job Id: 23736; Secondary Job Id: 0; Message: Reserving nodes in database; 
2019-02-18 12:37:25.997410     csmapi::info     | [1303405849]; Allocation ID: 7468; Primary Job Id: 23736; Secondary Job Id: 0; Message: Recording Allocation statistics to database; 
2019-02-18 12:37:26.026923     csmapi::info     | csm_allocation_create[1303405849]; Allocation ID: 7468; Primary Job Id: 23736; Secondary Job Id: 0; Message: Create Completed; 
2019-02-18 12:37:26.027059     csmapi::info     | [1303405849]; csm_allocation_create end
```
Because RHEL 7.6 is not officially supported in the CSM 1.5 up coming release, we lowered the sev. to 3.

**Comment by fpizzano** [comment]
Compute node log:


```
# grep 1303405849 csm_compute.log
[COMPUTE]2019-02-18 12:34:10.844227     csmapi::info     | [1303405849]; csm_allocation_create start
[COMPUTE]2019-02-18 12:34:10.844309     csmapi::info     | [1303405849]; Allocation ID: 7468; Primary Job Id: 23736; Secondary Job Id: 0; Message: Allocation enter running;
[COMPUTE]2019-02-18 12:34:10.974986     csmapi::info     | [1303405849]; Allocation ID: 7468; Message: Opening cgroups;
[COMPUTE]2019-02-18 12:36:47.993859     csmapi::info     | [1303405849]; Allocation ID: 7468; Message: Opened cgroups;
[COMPUTE]2019-02-18 12:36:47.994043     csmapi::info     | [1303405849]; Allocation ID: 7468; user_flags: ; system_flags: ; Message: Prolog start;
[COMPUTE]2019-02-18 12:37:18.076669     csmapi::info     | [1303405849]; Allocation ID: 7468; user_flags: ; system_flags: ; Message: Prolog success;
[COMPUTE]2019-02-18 12:37:18.076864     csmapi::info     | csm_allocation_create[1303405849]; Allocation ID: 7468; Primary Job Id: 23736; Secondary Job Id: 0; Error Code: 0; Error Message:
[COMPUTE]2019-02-18 12:37:18.076912     csmapi::info     | [1303405849]; csm_allocation_create end
#
```

**Comment by thanh-lam** [comment]
The last time we saw this timed out problem was on the IST alternate cluster that has only two compute nodes. The original time out threshold in csm_api.cfg was 120. But, when I ran a simple job like jlink or barrier, the job failed and node f10n15 was taken down to SOFT_FAILURE. Note: this only happened on f10n15. The second node, f10n16, was fine with time out threshold 120. Following are related messages in master.log:
```
2019-02-22 16:15:33.768045     csmapi::info     | [665236129]; Primary Job Id: 2209; Secondary Job Id: 0; Message: Requesting allocation in database;
2019-02-22 16:15:33.817417     csmapi::info     | [665236129]; Allocation ID: 365; Primary Job Id: 2209; Secondary Job Id: 0; Message: Reserving nodes in database;
2019-02-22 16:15:33.842309     csmapi::error    | csm_allocation_create[665236129]; Allocation ID: 365; Primary Job Id: 2209; Secondary Job Id: 0;Database Error Message: The following nodes were not available: f10n15 ;The following nodes were not found:  ; Message: Allocation is being reverted; Unable to reserve nodes; Message: Allocation was successfully reverted;
2019-02-22 16:15:33.842402     csmapi::info     | [665236129]; csm_allocation_create end
2019-02-22 16:15:33.866776     csmapi::info     | [1048721110]; csm_allocation_delete start
2019-02-22 16:15:33.867207     csmapi::error    | csm_allocation_delete[1048721110]; Primary Job ID: 2209Secondary Job ID: 0; Database check failed for user id 31415;
2019-02-22 16:15:33.867332     csmapi::info     | [1048721110]; csm_allocation_delete end
2019-02-22 16:15:44.031677     csmapi::info     | [1098477987]; csm_allocation_query_active_all start
2019-02-22 16:15:44.033332     csmapi::info     | [1098477987]; csm_allocation_query_active_all end
2019-02-22 16:15:44.038058     csmapi::info     | [568748509]; csm_allocation_create start 
```
Increasing time out to 1240 masked out the problem. Because this is only a two-node cluster that somehow has one node went `bad`. It's a good chance for us to do further debug now that CSM is released. Will change sev. back to 2 for debugging purposes and hopefully get to some conclusion or work-around.

**Comment by fpizzano** [comment]
Look like offline cores on the second socket are taking much longer, we may need help from the kernel people, can we open a bugzilla ? 

```
[root@f10n15 cpuset]# time echo 0 > /sys/devices/system/cpu/cpu78/online

real	0m0.165s
user	0m0.001s
sys	0m0.000s
[root@f10n15 cpuset]# time echo 0 > /sys/devices/system/cpu/cpu79/online

real	0m0.188s
user	0m0.001s
sys	0m0.000s
[root@f10n15 cpuset]# time echo 0 > /sys/devices/system/cpu/cpu80/online

real	0m1.658s
user	0m0.001s
sys	0m0.000s
[root@f10n15 cpuset]# time echo 0 > /sys/devices/system/cpu/cpu81/online

real	0m1.647s
user	0m0.001s
sys	0m0.000s
[root@f10n15 cpuset]# time echo 0 > /sys/devices/system/cpu/cpu82/online

real	0m1.661s
user	0m0.001s
sys	0m0.000s
[root@f10n15 cpuset]#
```

**Comment by fpizzano** [comment]
I opened bugzilla to track this problem:

https://bugzilla.linux.ibm.com/show_bug.cgi?id=176043

**Comment by thanh-lam** [comment]
Based on the comments from the bugzilla defect 176043, we'll have to wait for RHEL 8 to verify this issue. Lowering sev. to 4 for now.

**Comment by thanh-lam** [comment]
Raised sev. to 1 per request for investigating another node hang issue...

**Comment by mew2057** [comment]
Why was this raised to sev 1?

**Comment by thanh-lam** [comment]
Now that Fernando has opened another bugzilla defect to track the node hang problem:
[#176607](https://bugzilla.linux.ibm.com/show_bug.cgi?id=176607)
this issue should go back to sev.2 and be verified in CSM 1.5.3:
[#630](https://github.com/IBM/CAST/pull/630)

**Comment by thanh-lam** [comment]
Just an update for this issue with the latest CSM 1.5.3 level, after the nodes were rebooted and csm_compute.cfg had socket_order = 01, the first `allocation_create` took about 60 sec, with SMT = 4 and no core_isolation. Then, the subsequent `allocation_create` time took < a sec, with same SMT = 4 and no core_isolation. Note: Times displayed included 30 sec sleep in prolog.
```
 # ./readcnlog-root.sh
Alloc  Start date-time                    End date-time                         Jobid SMT  Time (sec)
1262 2019-04-16 14:38:35.088281 2019-04-16 14:40:06.729056 -- 4770 4       91s640775
1263 2019-04-16 14:52:10.320639 2019-04-16 14:52:40.618620 -- 4771 4       30s297981
```
Since we've not seen the 3 minutes time occurred recently, will lower sev. to 4 until the coming of RHEL 8 for further verification.

**Comment by thanh-lam** [comment]
"Re-investigate" this timeout issue after reboot with CSM 1.6.0 and a new RHEL 7.6 image (i.e. new kernel level and/or firmware). The impression is that some of the improvement in core blinking might have lost this time around. `allocation_create` (with no core-isolation) took about 2 mins.
```
[root@f4n05 bin]# time ./csm_allocation_create -j 1 -l f5n06 -n f10n15,f10n16
---
allocation_id: 25
num_nodes: 2
- compute_nodes: f10n15
- compute_nodes: f10n16
user_name: root
user_id: 0
state: running
type: user-managed
job_submit_time: 2019-05-03 10:22:47
...

real    1m59.405s
user    0m0.000s
sys    0m0.007s
```
Further experiments with powering off cpu's showed that the *slow cpu* might have moved. While last time the slow cpus were only in socket 1, this time socket 0 also showed *slow* cpus on the far left side  for example cpu 0, 4, 8, ...
```
[root@f10n16 sbin]# for i in 15 14 13 12;do(time echo 0 > /sys/devices/system/cpu/cpu$i/online);done

real    0m0.138s
user    0m0.002s
sys    0m0.000s

real    0m0.140s
user    0m0.002s
sys    0m0.000s

real    0m0.109s
user    0m0.002s
sys    0m0.000s

real    0m1.719s   <<< CPU 12 took more than 10x of the time compared to CPU 15, 14, 13.
user    0m0.002s
sys    0m0.000s
```

**Comment by besawn** [comment]
@thanh-lam Can you confirm whether this is still an issue on RHEL 8 or has this been resolved now?

**Comment by thanh-lam** [comment]
This has been a long time since we're now on RHEL 8. Obviously, we've not seen this but will do a quick test to confirm.

**Comment by thanh-lam** [comment]
A test with the same `csm_allocation_create` command returned in about 9 sec. This issue can be closed now.
```
[root@c685f4n07 bin]# time ./csm_allocation_create -j 1 -l f5n06 -n f10n15,f10n16
---
allocation_id: 299
num_nodes: 2
- compute_nodes: f10n15
- compute_nodes: f10n16
user_name: root
user_id: 0
state: running
type: user-managed
job_submit_time: 2021-03-16 11:06:02
...

real	0m9.596s
user	0m0.005s
sys	0m0.004s
```

**Comment by besawn** [comment]
@thanh-lam Thank you!
