### ISSUE TITLE
CSM_FVT Test Case: csm_allocation_update state, private test

### ISSUE THREAD

**Issue by mew2057** [IBM/CAST#58]
`csm_allocation_update_state` needs a regression case for private allocations. 

The test should have a flow something like this:

- [x] Create an allocation as a non-root user (A) in the  `staging-in` state.
- [x] Attempt to transition the state from `staging-in` to `running`  as another non-root user (B), the API should reject.
- [x] Attempt to transition the state from `staging-in` to `running`  as the proper user (A), API should accept.
- [x] `csm_allocation_query_details` should have a `staging-in`, `to-running` and `running` state.
- [x] Attempt to transition the state from `running` to `staging-out`  as another non-root user (B), the API should reject.
- [x] Attempt to transition the state from `staging-in` to `running`  as the proper user (A), API should accept.
- [x] `csm_allocation_query_details` should have a `staging-in`, `to-running`, `running`, `to-staging-out` and `staging-out` state.
- [x] Delete the allocation.

**Comment by pdlun92** [comment]
PR #57

**Comment by mew2057** [comment]
Merge completed.

**Comment by pdlun92** [comment]
#57 was merged as well as the regression pull request.  Closing this issue
