### ISSUE TITLE
bb: slow performance when multiple nodes share a single transfer handle

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#581]
**Describe the bug**
Performance falls off when scaling a test case in which all MPI processes use a shared handle when compared to using a unique handle per process.  In this test, one MPI process runs per compute host (node) and each process transfers a single file from the SSD to GPFS.  A recent test shows the following:

unique handle per node:
- 128 nodes: 12.7 sec = 10.1 GB/s (job 90424, 1GB files)
- 256 nodes: 18.4 sec = 13.9 GB/s (job 90421, 1GB files)
- 640 nodes: 29 secs = 22.1 GB/s (job 90411, 1GB files)
 
shared handle across nodes:
- 128 nodes: 169 secs = 7.57 GB/s (job 90379, 10GB files)
- 256 nodes: 554 secs = 4.62 GB/s (job 90388, 10GB files)
- 640 nodes: 2395 sec = 0.27 GB/s (job 90392, 1GB files)

**To Reproduce**
The C programs to reproduce these results have been passed to @tgooding 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Machine [LLNL: lassen]
 - Version [BB 1.4.1]

**Additional context**

**Issue Source:**
Reasoning for opening this issue; a description of why this issue was opened; a link to another thread that spawned the need for opening this issue.

**Comment by tgooding** [comment]
This is believed to be addressed by the commits in pull request #574

**Comment by adammoody** [comment]
With the latest software, we get the following numbers:

unique:
- 128 nodes: 9.71 secs = 13.2 GB/s (job 133022, 1GB files)
- 256 nodes: 14.2 secs = 18.0 GB/s (job 133130, 1GB files)
- 400 nodes: 19.8 secs = 20.2 GB/s (job 133133, 1GB files)
- 512 nodes: 22.9 secs = 22.4 GB/s (job 133261, 1GB files)
- 640 nodes: 24.5 secs = 26.1 GB/s (job 133258, 1GB files)

shared:
- 16 nodes: 3.8 secs = 4.2 GB/s (job 132814, 1GB files)
- 128 nodes: 12.6 secs = 10.2 GB/s (job 132817, 1GB files)
- 256 nodes: 28.2 secs = 9.1 GB/s (job 132820, 1GB files)
- 400 nodes: 45.3 secs = 8.8 GB/s (job 132902, 1GB files)
- 512 nodes: 68.4 secs = 7.5 GB/s (job 133252, 1GB files)
- 640 nodes: 92.4 secs = 6.9 GB/s (job 133254, 1GB files)

shared (from before):
* 128 nodes: 169 secs = 7.57 GB/s (job 90379, 10GB files)
* 256 nodes: 554 secs = 4.62 GB/s (job 90388, 10GB files)
* 640 nodes: 2395 sec = 0.27 GB/s (job 90392, 1GB files)

So there is a big improvement, e.g., shared 640 nodes increased from 0.27 GB/s to 6.9 GB/s.

However, it is still notably slower than the unique case (6.9 vs 26.1), and more worrisome is that it still seems to top out and trend back down with increasing node count.

We've given the raw output files to @tgooding as well as some bbserver logs.

**Comment by tgooding** [comment]
The improvements showed shared performance within 2.5% of unique handle.  Think this issue can be closed.
