### ISSUE TITLE
bb prestage: hang during multi-host test with stage in script

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#582]
**Describe the bug**
A stage in script that attempts to copy a single file to the SSD of each compute host hangs during the stage in phase.  Upon inspection, it appeared as though 1 of the 16 hosts had succeeded in copying the file, while 15 of the 16 had not started.

**To Reproduce**

Stage in script:
```
#!/usr/bin/perl
use JSON;
use Cwd 'abs_path';
use Cwd;
use File::Basename;
BEGIN
{
    ($dir,$fn) = $0 =~ /(\S+)\/(\S+)/;
    unshift(@INC, abs_path($dir));
}
use lib '/opt/ibm/bb/scripts';
use bbtools;

print "*** Entering user stage-in script ***\n";

$WORKING_DIR = getcwd();
print "CWD = $WORKING_DIR\n";

$USER_STGIN_LISTFILE = $ENV{"USER_STGIN_LISTFILE"};
$USER_PFS_PATH = $ENV{"USER_PFS_PATH"};

if ("$USER_STGIN_LISTFILE" ne "") {
    if (! open($IN_LIST, '<', $USER_STGIN_LISTFILE)) {
	die "Could not open input list_file $USER_STGIN_LISTFILE\n";
    }

    $PRESTAGE_TDEF = `mktemp /p/gpfs1/username1/prestage_tdef_XXXX`;
    chomp $PRESTAGE_TDEF;
    if (! open($TDEF, '>', $PRESTAGE_TDEF)) {
	die "Could not open transfer definition file $PRESTAGE_TDEF\n";
    }

    while ($LINE = <$IN_LIST>) {
	chomp $LINE;
	($SOURCE, $TARGET) = split /\s+/, $LINE;
        if ($SOURCE !~ /^\//) {
            $SOURCE = abs_path($SOURCE);
        }
	$SOURCE =~ s/<PFS>/$USER_PFS_PATH/;
        $TARGET = $BBPATH . "/" . basename($SOURCE);
	$TARGET =~ s/<BB>/$BBPATH/;
	print "SOURCE=$SOURCE, TARGET=$TARGET\n";
	print $TDEF "$SOURCE $TARGET 0\n";
    }

    close $IN_LIST;
    close $TDEF;

    $LAST_NODE = scalar(@HOSTLIST_ARRAY) - 1;
    $CONTRIBS = `seq -s, 0 $LAST_NODE`;
    chomp $CONTRIBS;

    $result = bbcmd("$TARGET_NODE0 gethandle --tag=1 --contrib=$CONTRIBS");
    print "$result->{'0'}{'out'}{'transferHandle'}\n";
    bbcmd("$TARGET_ALL copy --handle=$result->{'0'}{'out'}{'transferHandle'}" .
	  " --filelist=$PRESTAGE_TDEF");

    system("rm -f $PRESTAGE_TDEF");
}

print "*** Exiting user stage-in script ***\n";
```

Run command:
```
export USER_STGIN_LISTFILE=/p/gpfs1/username1/bcast_list.txt
bsub -G guests -q pall -nnodes 16 -stage 'storage=100:in=/p/gpfs1/username1/stagein_bcast.pl' testbcast.bsub
```

The job gets stuck in prestage, and bhist -l shows the following:
```
Wed Feb 13 13:13:34: External Message "BB: Waiting for 1 transfer(s) to complet
                     e" was posted from "root" to message box 120;
Wed Feb 13 13:13:39: External Message "BB: Waiting for 1 transfer(s) to complet
                     e" was posted from "root" to message box 120;
Wed Feb 13 13:13:44: External Message "BB: Waiting for 1 transfer(s) to complet
                     e" was posted from "root" to message box 120;
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Machine [lassen]
 - Version [BB 1.4.1]

**Additional context**

**Issue Source:**
Reasoning for opening this issue; a description of why this issue was opened; a link to another thread that spawned the need for opening this issue.

**Comment by tgooding** [comment]
The $TARGET_ALL adds a `--bcast` to the copy.  Which causes the same command to get echo'd down to all compute nodes.  While this is an efficient way to transmit the command, it currently loses the rank information.  That rank information is needed by the copy command to attribute the transfer with the right contribID.  As this command is using a single transfer handle with multiple contributors (i.e., contribIDs 0,1,2,3,4,...).  The first one to each bbServer is successful, the other n-1 contributors fail with "already started".

**Comment by adammoody** [comment]
Verified that removing the --bcast option works around the problem.  Test below was transferring a the same 1GB file from GPFS to the BB on each node.

bbcmd cost (from "Calling user stage-in script" to "User stage-in script exited"):
- 16 nodes: < 1sec
- 128 nodes: 6 secs
- 256 nodes: 15 secs
- 512 nodes: 48 secs
- 640 nodes: 71 secs

file transfer cost (likely buffered in page cache on bbserver from GPFS, from "User stage-in script exited" to "Stage-in admin script completed"):
- 16 nodes: 16 secs = 1 GB/s
- 128 nodes: 51 secs = 2.51 GB/s
- 256 nodes: 77 secs = 3.3 GB/s
- 512 nodes: 67 secs = 7.6 GB/s
- 640 nodes: 67 secs = 9.6 GB/s

Are there plans to incorporate contribid back into the bcast?

**Comment by tgooding** [comment]
--bcast would need a way to lookup its contribid.  I don't think that information is known locally on the compute node and a lookup would be expensive.  So don't have a design at the moment that could do that.  Don't use the --bcast option when that information is critical.  

I recall there were some changes to the example scripts, so setting to verify.

**Comment by tgooding** [comment]
Force close, reopen if this is not working.
