### ISSUE TITLE
csm_ssd_wear_history table has a field containing null: data.archive_history_time

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#595]
**Describe the bug**
When displaying the csm_ssd_wear_history data records in kibana, the field `data.archive_history_time` contains a `null` value. That results in `undefined` or `question mark` data type in kibana. Refreshing the index didn't fix it.

**To Reproduce**
1. Go to Discover in kibana and select `cast-db-csm_ssd*` index.
2. Select one of the records and list detail data.
3. Scroll down and find the data field `data.archive_history_time` .
4. See the ? data type and an ! for the data value.

**Expected behavior**
This data field should have a valid data type and a value such as date and time. If this field is not used, remove it.

**Screenshots**

**Environment (please complete the following information):**
 - Machine [bd01, bd02, f4n05]
 - Version [CSM 1.5.0-2137]

**Additional context**
The data record can also be extracted from the JSON files in `/var/log/ibm/csm/archive/.
```
{
   "data": {
       "archive_history_time": null,
       "history_time": "2019-02-26 15:48:48.749763",
       "node_name": "f3n03",
       "operation": "U",
       "serial_number": "S3RVNA0J300727",
       "wear_lifespan_used": -1.0,
       "wear_percent_spares_remaining": -1.0,
       "wear_total_bytes_read": -1,
       "wear_total_bytes_written": -1
   },
   "type": "db-csm_ssd_wear_history"
}
```

**Issue Source:**
IST tests for SSD wear data.

**Comment by NickyDaB** [comment]
Based off my understanding, that field holds the time when the database record was archived or "backed up". If it is "null", then it is my understanding that the record was never archived or backed up. 

@williammorrison2 and @mew2057  may know more. 

But question about the functionality. If this database record has been moved into big data, should this record's archive time be updated with the time it was stored into big data? Or does this field specifically refer to the archive script? As a cluster may not have big data component attached. which makes sense. but should we consider big data archiving to be a sub category of the standard archive, which if we do, then maybe we want to change that field to say the record was indeed backed up?

**Comment by thanh-lam** [comment]
This "null" history time also shows up in other archived tables like ib_cable. As in the following json source, there are other three timestamps that are good:
   * discovery_time: "2019-04-30 09:37:38.585673"
   * collection_time: "2019-05-14 14:29:58.471150"
   * history_time: "2019-05-14 14:29:58.471150"
Collection time and history time are the same. Archive time must be the time that the `csm_db_history_archive.py` was run then.

```
    "source": "/var/log/ibm/csm/archive/csm_ib_cable_history.archive.2019-05-14.json",
    "data": {
      "part_number": "N/A",
      "port_s2": "1",
      "guid_s1": "ec0d9a03000c4110",
      "operation": "U",
      "guid_s2": "ec0d9a03000c4118",
      "discovery_time": "2019-04-30 09:37:38.585673",
      "serial_number": "N/A",
      "revision": "N/A",
      "collection_time": "2019-05-14 14:29:58.471150",
      "width": "IB_4x",
      "name": "ec0d9a03000c4110_37:ec0d9a03000c4118_1",
      "length": "N/A",
      "archive_history_time": null,
      "type": "NA - UNKNOWN",
      "history_time": "2019-05-14 14:29:58.471150",
      "port_s1": "37",
      "severity": "Info",
      "comment": "comment",
      "identifier": "Unknown"
    },
```
