### ISSUE TITLE
BB gitcommit version mismatch message displayed via libbbapi

### ISSUE THREAD

**Issue by tgooding** [IBM/CAST#596]
@adammoody ran an older (but ABI compatible) built-binary that dynamically loaded the installed (latest) libbbapi.so.  There was a version check that ended up outputting a warning to the application's console.  

I would guess that we are checking the version before we load the JSON configuration for libbbapi.  So boost::Log is using the unconfigured defaults.  @meahoibm : can you look?  Thanks!

**Comment by meahoibm** [comment]
The logging occurs on the throw from version_check in BB_InitLibrary2 before the initializeLogging in BB_InitLibrary2.  Working on setting up logging before the version_check.

**Comment by tgooding** [comment]
Should this be in verify?

**Comment by meahoibm** [comment]
Moved to verify.

**Comment by tgooding** [comment]
Verified, closing.
