### ISSUE TITLE
CSM_FVT Test Case: csm_ctrl_cmd reset option

### ISSUE THREAD

**Issue by lasch** [IBM/CAST#61]
Test case for pull request #60 

Steps for test case:
* get a compute node to use the configured secondary as the primary connection
  * either by restarting the primary
  * or by starting the secondary first, then start compute; then start primary
* run health-check on master/utility to confirm that primary node is linked as secondary:
```
/csm_infrastructure_health_check -v
       ...
    AGGREGATOR: primaryhost (bounced=0; version=1.1.0)
       ...
	Primary Nodes:
		Active: 1
			COMPUTE: computehost (bounced=0; version=1.1.0; link=SECONDARY)
```
* run ctrl-cmd on compute: ```csm_ctrl_cmd --agg.reset```
* run health-check again to confirm link status matches configured status:
```
csm_infrastructure_health_check -v
       ...
    AGGREGATOR: primaryhost (bounced=0; version=1.1.0)
       ...
	Primary Nodes:
		Active: 1
			COMPUTE: ichonsocks (bounced=0; version=1.1.0; link=PRIMARY)
```

Progress:
- [x] Test Case Design
- [x] Manual run
- [x] Approval
- [ ] Integrate to regression

**Comment by lasch** [comment]
Oh, I think, I forgot to mention all the "try to break it"-cases for example:
* run with single primary aggregator only - command should have no effect
* run with the secondary being active only - command should have no effect
* run with primary/secondary as configured - command should have no effect

(no effect would hopefully include: aggregator(s) survive; node still reachable; no RAS events; maybe an info/warning log line in compute or aggregator logs about an unnecessary attempt to reset the aggregator connection status)

**Comment by pdlun92** [comment]
Started working on the basic (success path) regression bucket right now, hope to have it done shortly

**Comment by pdlun92** [comment]
Finished the basic bucket
