### ISSUE TITLE
Burst Buffer allocations not working on Butte cluster @ LLNL

### ISSUE THREAD

**Issue by gzjfn4** [IBM/CAST#626]
From: Thomas Gooding <tgooding@us.ibm.com>
Sent: Wednesday, March 27, 2019 2:16 PM
To: Moody, Adam T. <moody20@llnl.gov>
Cc: Bertsch, Adam <bertsch2@llnl.gov>; Casses, Ben <casses1@llnl.gov>; Fox, Dave <fox18@llnl.gov>; Goldstone, Robin J. <goldstone1@llnl.gov>; Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Hutter, Tony <hutter2@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>; Shoga, Kathleen <shoga1@llnl.gov>; Watson, Py <watson30@llnl.gov>
Subject: Re: BB Issue on butte - disconnect from bbserver

 

Correct, there is no bbServer connection.  Either it never could connect, or the bbproxy->bbserver hello message failed.  

If the admin runs this command on the compute node:

$  bbcmd getserver --connected=active  --pretty | grep serverList

It should return either one of the primary or backup VMs.  You can see which one is primary or backup via:

$  bbcmd getserver --connected=primary --pretty | grep serverList
$  bbcmd getserver --connected=backup  --pretty | grep serverList

On the VM side.  You should see bbServer running and "nvme list" should show connections to each compute node.  

Tom

From:        "Moody, Adam T." <moody20@llnl.gov>
To:        Thomas Gooding <tgooding@us.ibm.com>, "Hutter, Tony" <hutter2@llnl.gov>, "Watson, Py" <watson30@llnl.gov>, "Lamb, James Lewis" <lamb28@llnl.gov>, "Fox, Dave" <fox18@llnl.gov>, "Goldstone, Robin J." <goldstone1@llnl.gov>
Cc:        "Gonsiorowski, Elsa" <gonsiorowski1@llnl.gov>, "Shoga, Kathleen" <shoga1@llnl.gov>, "Casses, Ben" <casses1@llnl.gov>, "Bertsch, Adam" <bertsch2@llnl.gov>
Date:        03/27/2019 04:03 PM
Subject:        Re: BB Issue on butte - disconnect from bbserver

Hi Tom,
I'm seeing this bit from the bbproxy log on the node where Tony was trying to run:

2019-03-27 13:03:16.271462         bb::error    | SendMessageWithReply--Unable to find connection to 'bbserver'
2019-03-27 13:03:16.271490         bb::error    | sendMessage to server failed
2019-03-27 13:03:16.271608         bb::info     | Attempting backout via removeLogicalVolume of mountpoint = /mnt/bb_af4f57fc49b2dbd2cbf952b690d0235e
2019-03-27 13:03:16.271638         bb::info     | Removed logical volume for Uuid 'f78ed29e-c16b-4ea3-a656-dc6f98413bad'
2019-03-27 13:03:16.283050         bb::info     | Lookup of jobid(38148,0) ==> AllocationID 21572
2019-03-27 13:03:16.285593         bb::error    | Error posting csm_bb_lv_delete().  rc=25
2019-03-27 13:03:16.358378         bb::always   | Executing: lvchange --activate n /dev/bb/bb_11 2>&1;
2019-03-27 13:03:16.417608         bb::always   | Executing: lvremove -vf /dev/bb/bb_11;
2019-03-27 13:03:16.427390         bb::info     |   Logical volume "bb_11" successfully removed
2019-03-27 13:03:16.428192         bb::info     | ==> Sending msg to bb.api73910: BB_CREATELOGICALVOLUME, msg#=485, rqstmsg#=5 CnxSockUnix=/run/bb_socket
2019-03-27 13:03:16.546446        txp::always   | CnxSockUnix::accept(p) CnxSockUnix=/run/bb_socket sockfd=28
2019-03-27 13:03:16.546490        txp::info     | Credentials: pid= 73961, uid= 0, gid= 0
2019-03-27 13:03:16.548409         bb::error    | bberror: {"id":"372","rc":"-1","env":{"jobid":"38148","jobstepid":"1","contribid":"0"},"in":{"apicall":"BB_CreateLogicalVolume","parms":{"mount":"\/mnt\/bb_af4f57fc49b2dbd2cbf952b690d0235e","size":"1G","flags":"1"},"misc":{"uid":"0","gid":"0","hostname":"butte21"}},"butte21:bb_api73910":{"breadcrumbs":{"LVUtils":{"getUserAndGroupIds":{"entry":{"count":"1","ts":"27 13:03:15.199699"},"exit":{"count":"1","ts":"27 13:03:15.199765"}},"createLogicalVolume":{"entry":{"count":"1","ts":"27 13:03:15.199856"},"attempts":{"count":"1","ts":"27 13:03:15.203184"},"exit":{"count":"1","ts":"27 13:03:16.271132"}},"getNumberOfSectors":{"entry":{"count":"1","ts":"27 13:03:15.199938"},"exit":{"count":"1","ts":"27 13:03:15.200001"}},"isMounted":{"entry":{"count":"2","ts":"27 13:03:15.200062"},"mounts_processed":{"count":"139","ts":"27 13:03:16.288735"},"exit":{"count":"2","ts":"27 13:03:16.288799"}},"logicalVolumeExists":{"entry":{"count":"1","ts":"27 13:03:15.203368"},"exit":{"count":"1","ts":"27 13:03:15.216620"}},"doCreateLogicalVolume":{"entry":{"count":"1","ts":"27 13:03:15.216691"},"exit":{"count":"1","ts":"27 13:03:15.228241"}},"doChangeLogicalVolume":{"entry":{"count":"2","ts":"27 13:03:15.228311"},"exit":{"count":"2","ts":"27 13:03:16.417484"}},"doInitializeFileSystem":{"entry":{"count":"1","ts":"27 13:03:15.814942"},"exit":{"count":"1","ts":"27 13:03:16.251275"}},"doMount":{"entry":{"count":"1","ts":"27 13:03:16.251346"},"attempts":{"count":"1","ts":"27 13:03:16.251416"},"exit":{"count":"1","ts":"27 13:03:16.270916"}},"doChangeOwner":{"entry":{"count":"1","ts":"27 13:03:16.270988"},"exit":{"count":"1","ts":"27 13:03:16.271067"}},"removeLogicalVolume":{"entry":{"count":"1","ts":"27 13:03:16.285706"},"exit":{"count":"1","ts":"27 13:03:16.427555"}},"doUnmount":{"entry":{"count":"1","ts":"27 13:03:16.288851"},"exit":{"count":"1","ts":"27 13:03:16.358300"}},"doRemoveLogicalVolume":{"entry":{"count":"1","ts":"27 13:03:16.417544"},"exit":{"count":"1","ts":"27 13:03:16.427487"}}},"bbproxy":{"incr":{"entry":{"count":"1","ts":"27 13:03:15.203248"},"exit":{"count":"1","ts":"27 13:03:15.203306"}},"msgin_createlogicalvolume":{"exit":{"count":"1","ts":"27 13:03:16.427630"}},"msgin_setvar":{"entry":{"count":"1","ts":"27 13:03:16.547787"}}}}},"out":{"lvuuid":"f78ed29e-c16b-4ea3-a656-dc6f98413bad"},"error":{"text":"sendMessage to server failed","func":"msgin_createlogicalvolume","line":"1230","sourcefile":"\/home\/ppsbld\/workspace\/PUBLIC_CAST_V1.5.x_ppc64LE_RH7.5_ProdBuild\/bb\/src\/bbproxy.cc"},"err":{"csmerror":"Error posting csm_bb_lv_delete()","csmrc":"25"}}

Seems like this node can't talk to its bbserver?
-Adam

﻿On 3/27/19, 1:26 PM, "Moody, Adam T." <moody20@llnl.gov> wrote:

   Hi Robin,
   This is one thread I was thinking of.  Looks like you're the only one missing from it.
   
   Anyway, looking back through this, there is a sequence of "fixed" / "now broken again" states involved.
   
   One thing I gather is that It looks like we have to manually mount GPFS on the bbservers still.  Was that done after the butte update?
   
   Tom, did you find the cause of the other problem Dave mentions below on march 20 for which he grabbed some logs?  I don't see your reply in this thread.
   -Adam
   
   
   On 3/27/19, 8:55 AM, "Hutter, Tony" <hutter2@llnl.gov> wrote:
   
       > Fox can likely check that out on Thursday if it is still broken.
       
       Just tried it today: "There are no suitable hosts for the job".
       
       
       On 3/27/19 1:34 AM, Watson, Py wrote:
       > butte has been updated to BlueOS 3.2-26 with CUDA 10.1.  CUDA 10.1 is not recommended by IBM for production yet, but should be usable on butte.  The default for BlueOS 3.2-26 remains CUDA 9.2.  There is CSM and LSF configuration to be done to take full advantage of CSM 1.5, but my MPI hello world program ran without incident.  BurstBuffer may or may not be usable.  The bbServers are up.  Fox can likely check that out on Thursday if it is still broken.  LSF is at the latest version which IBM believes fixes the mbatchd crashes on lassen.  Unfortunately, they do not happen anywhere else, so real testing won't occur until lassen is updated.
       >
       > ==Py
       >
       > On 3/26/19, 07:25, "Hutter, Tony" <hutter2@llnl.gov> wrote:
       >
       >      The butte burst buffer is still down.  Can someone please take a look?  :
       >      
       >      
       >      On 3/22/19 3:14 PM,
       >      *********************************************************************************************************************************
       >        * JOBID    SLOTS    PTILE    HOSTS    USER STATE
       >      PRIO        QUEUE        GROUP REMAINING        LIMIT *
       >        *********************************************************************************************************************************
       >          37994       40       40        1    hutter2 NOHOSTS
       >      550.04       pbatch       guests -     04:00:00
       >      
       >      
       >        PENDING REASONS:
       >        There are no suitable hosts for the job;
       >      
       >      -Tony
       >      
       >      
       >        Lamb, James Lewis wrote:
       >      > Try again Tony,
       >      >
       >      > Gpfs was down on the VMs.
       >      >
       >      > I brought gpfs up and mounted the file system.
       >      >
       >      > James
       >      >
       >      > -----Original Message-----
       >      > From: Hutter, Tony <hutter2@llnl.gov>
       >      > Sent: Friday, March 22, 2019 3:03 PM
       >      > To: Moody, Adam T. <moody20@llnl.gov>; Fox, Dave <fox18@llnl.gov>
       >      > Cc: Thomas Gooding <tgooding@us.ibm.com>; Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>; Casses, Ben <casses1@llnl.gov>
       >      > Subject: Re: BB Issue on butte - disconnect from bbserver
       >      >
       >      > Lassen is back, but I still can't allocate a BB node.  I'm getting the usual "There are no suitable hosts for the job" even though there are nodes free.  Is anyone else able to allocate a BB node on either lassen or butte?
       >      >
       >      >
       >      > On 3/22/19 10:58 AM, Moody, Adam T. wrote:
       >      >> Hi Tony,
       >      >> Lassen worked for me yesterday, so you should be able to get nodes there.
       >      >> -Adam
       >      >>
       >      >> On 3/22/19, 9:56 AM, "Fox, Dave" <fox18@llnl.gov> wrote:
       >      >>
       >      >>       Don’t have a fix or work around yet. You can try getting nodes on
       >      >> passenger as it worked yesterday for Adam’s bb testing
       >      >>
       >      >>       Sent from my iPhone
       >      >>
       >      >>       > On Mar 22, 2019, at 9:49 AM, Hutter, Tony <hutter2@llnl.gov> wrote:
       >      >>       >
       >      >>       > Any updates on this?  I still can't reserve a node on butte...
       >      >>       >
       >      >>       >> On 3/20/19 12:16 PM, Fox, Dave wrote:
       >      >>       >> Tom, I got a report that BB allocations were not working on Butte today.  Tony is doing some test/dev work and it was working for him yesterday.
       >      >>       >> Tracing through the logs related to his job #37695, I see butte21 lost connection with butte1-vm1 about 8am.  But I can't tell from the logs why.
       >      >>       >>
       >      >>       >> Can you look at the logs files I put in your GPFS space on butte (listed below) and give us a clue of what might have gone wrong?
       >      >>       >>
       >      >>       >> Tom or James do we need a PMR to track this issue officially?
       >      >>       >>
       >      >>       >> David Fox
       >      >>       >>
       >      >>       >> [root@butte21:gooding3]# ls -ltrah
       >      >>       >> total 2.4M
       >      >>       >> drwxr-xr-x 441 root     root     256K Mar 20 08:05 ..
       >      >>       >> -rw-r-----   1 gooding3 gooding3 1.9M Mar 20 12:11 job-37695-butte1-vm1-bbserver-console_20190320.0.log
       >      >>       >> -rw-------   1 gooding3 gooding3 115K Mar 20 12:11 job-37695-bb_stagein.log
       >      >>       >> -rw-r-----   1 gooding3 gooding3 330K Mar 20 12:12 job-37695-butte21-bbproxy-console_20190320.0.log
       >      >>       >>
       >      >>       >> -----Original Message-----
       >      >>       >> From: Fox, Dave
       >      >>       >> Sent: Wednesday, March 20, 2019 12:09 PM
       >      >>       >> To: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>; Casses, Ben <casses1@llnl.gov>
       >      >>       >> Subject: RE: Can't reserve node on butte
       >      >>       >>
       >      >>       >> Something broke but it is not obvious yet.
       >      >>       >>
       >      >>       >> The first logs are in /var/log/bb_stagein.log on the launch node butte5 in this case.
       >      >>       >>
       >      >>       >> In that file you can find the job number (37695 ) and see what is logged wrt that job, it gets a failed message but it is not very useful.  The good news is you have only one node requested so I got to node21 and look in /var/log/bbproxy/console* where I see these errors:
       >      >>       >>
       >      >>       >> 2019-03-20 09:36:28.593378         bb::error    | SendMessageWithReply--Unable to find connection to 'bbserver'
       >      >>       >> 2019-03-20 09:36:28.593406         bb::error    | sendMessage to server failed
       >      >>       >>
       >      >>       >> Looking back futher in the logs and things may have been broken for a while this for example this message a 8am looks like a some kind of network failure, or process failed, and thus the client disconnected from the server:
       >      >>       >>
       >      >>       >> 2019-03-20 08:00:02.077541         bb::error    | RAS: {"id":"126","rc":"-1","error":{"executable":"\/opt\/ibm\/bb\/scripts\/nvmfConnect.sh","errno":"0","strerror":"Success","text":"There are zero remaining viable devices between bbProxy and bbServer","func":"removeDeviceSerial","line":"554","sourcefile":"\/u\/tgooding\/cast_proto1.5\/CAST\/bb\/src\/serial.cc","timediff":"2","remote":{"gmt":"Wed Mar 20 15:00:00 2019\n","epoch":"1553094000"},"local":{"gmt":"Wed Mar 20 15:00:02 2019\n","epoch":"1553094002"},"threshold":{"seconds":"1"},"serial":{"num":"0"}},"msgid":"bb.net.noViableDevices","butte1-vm1:bb_proxyL_166 (192_168_128_21)":{"breadcrumbs":{"bbserver":{"msgin_hello":{"exit":{"count":"1","ts":"20 08:00:02.068996"}}}}}}
       >      >>       >>
       >      >>       >> Now have to go to the server nodes butte1-vm1.
       >      >>       >>
       >      >>       >> The logs on that node are in /var/log/bbserver/console*
       >      >>       >>
       >      >>       >> I see logs of exceptions, then it looks like the RDMA protocol gets disconnected and tries to restart.
       >      >>       >>
       >      >>       >> I will capture all these logs and open a ticket with IBM to see if they can tell what happened.
       >      >>       >>
       >      >>       >> Tony were you testing at 8am this morning?
       >      >>       >>
       >      >>       >> I will restart the service after I have gathered everything up and see if that gets things going again.
       >      >>       >>
       >      >>       >> David Fox
       >      >>       >>
       >      >>       >> -----Original Message-----
       >      >>       >> From: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >> Sent: Wednesday, March 20, 2019 11:18 AM
       >      >>       >> To: Fox, Dave <fox18@llnl.gov>
       >      >>       >> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>
       >      >>       >> Subject: Re: Can't reserve node on butte
       >      >>       >>
       >      >>       >> Yea, it worked after your fix yesterday.
       >      >>       >>
       >      >>       >>> On 3/20/19 11:08 AM, Fox, Dave wrote:
       >      >>       >>> Did it work for you at all yesterday, I never got a chance to verify things were working.
       >      >>       >>>
       >      >>       >>> -----Original Message-----
       >      >>       >>> From: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >>> Sent: Wednesday, March 20, 2019 9:40 AM
       >      >>       >>> To: Fox, Dave <fox18@llnl.gov>
       >      >>       >>> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen
       >      >>       >>> <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>
       >      >>       >>> Subject: Re: Can't reserve node on butte
       >      >>       >>>
       >      >>       >>> Butte is broken again...  Dave can you fix it?  And can you list the
       >      >>       >>> commands you used to fix it?  That way I won't have to bug you about
       >      >>       >>> it anymore (I have root on butte)
       >      >>       >>>
       >      >>       >>> Thanks
       >      >>       >>>
       >      >>       >>> -Tony
       >      >>       >>>
       >      >>       >>>    **********************************
       >      >>       >>>    * Host:    - butte - butte5      *
       >      >>       >>>    * Date:    - 03/20/2019 09:30:20 *
       >      >>       >>>    * Cmd:     - lsfjobs -L          *
       >      >>       >>>    **********************************
       >      >>       >>>
       >      >>       >>>    *********************************************************************************************************************************
       >      >>       >>>    * JOBID    SLOTS    PTILE    HOSTS    USER STATE PRIO        QUEUE        GROUP REMAINING        LIMIT *
       >      >>       >>>    *********************************************************************************************************************************
       >      >>       >>>      37674       40       40        1    hutter2 STAGEFAIL
       >      >>       >>> 550.04       pbatch       guests -     04:00:00
       >      >>       >>>
       >      >>       >>>
       >      >>       >>>    ***************************************************************
       >      >>       >>>    * HOST_GROUP       TOTAL   DOWN    RSVD   BUSY   FREE HOSTS *
       >      >>       >>>    ***************************************************************
       >      >>       >>>      batch_hosts         16      2       0      0     14 butte[11-26]
       >      >>       >>>      debug_hosts          2      0       0      0      2 butte[9-10]
       >      >>       >>>      launch_hosts         1      0       0      0      1 butte[5]
       >      >>       >>>
       >      >>       >>>
       >      >>       >>>    *****************************************************************************************************
       >      >>       >>>    * QUEUE          TOTAL  DOWN   RSVD/BUSY   FREE DEFAULTTIME MAXTIME  STATE     HOST_GROUP(S) *
       >      >>       >>>    *****************************************************************************************************
       >      >>       >>>      exempt            19     2           0     17 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>      expedite          19     2           0     17 30:00      8:00:00 Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>      pall              19     2           0     17 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>      pbatch            17     2           0     15 30:00      8:00:00 Active    launch_hosts,batch_hosts
       >      >>       >>>      pdebug             3     0           0      3 30:00      1:00:00 Active    launch_hosts,debug_hosts
       >      >>       >>>      standby           19     2           0     17 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>      transfer           1     0           0      1 None    Unlimited
       >      >>       >>> Active    launch_hosts
       >      >>       >>>
       >      >>       >>>> On 3/19/19 11:24 AM, Fox, Dave wrote:
       >      >>       >>>> I think this is fixed now but could not test as all nodes are in use.
       >      >>       >>>>
       >      >>       >>>> The VM servers did not have GPFS mounted.  They do not automount on boot since they are client nodes like the compute nodes.  But running nodeup like we do on normal compute nodes does the right thing, so we need to have that be part of the process when working on the gpfs VM nodes.
       >      >>       >>>>
       >      >>       >>>> -----Original Message-----
       >      >>       >>>> From: Fox, Dave
       >      >>       >>>> Sent: Tuesday, March 19, 2019 9:49 AM
       >      >>       >>>> To: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >>>> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen
       >      >>       >>>> <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>
       >      >>       >>>> Subject: RE: Can't reserve node on butte
       >      >>       >>>>
       >      >>       >>>> Sorry have not looked yet was in class yesterday and did not get to it.  Will try to check it out this morning.
       >      >>       >>>>
       >      >>       >>>> -----Original Message-----
       >      >>       >>>> From: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >>>> Sent: Tuesday, March 19, 2019 9:45 AM
       >      >>       >>>> To: Fox, Dave <fox18@llnl.gov>
       >      >>       >>>> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>; Shoga, Kathleen
       >      >>       >>>> <shoga1@llnl.gov>; Lamb, James Lewis <lamb28@llnl.gov>
       >      >>       >>>> Subject: Re: Can't reserve node on butte
       >      >>       >>>>
       >      >>       >>>> I tried again and still can't reserve a node on butte (still getting STAGEFAIL).
       >      >>       >>>>
       >      >>       >>>> Dave, any additional ideas?
       >      >>       >>>>
       >      >>       >>>> $ bsub -nnodes 1   -stage storage=1 -Is -XF -G guests -core_isolation 2 /usr/tce/packages/lalloc/lalloc-2.0/bin/lexec bash Job <37489> is submitted to default queue <pbatch>.
       >      >>       >>>> <<ssh X11 forwarding job>>
       >      >>       >>>> <<Waiting for dispatch ...>>
       >      >>       >>>>
       >      >>       >>>> $ lsfjobs -L
       >      >>       >>>>
       >      >>       >>>>     **********************************
       >      >>       >>>>     * Host:    - butte - butte5      *
       >      >>       >>>>     * Date:    - 03/19/2019 09:43:59 *
       >      >>       >>>>     * Cmd:     - lsfjobs -L          *
       >      >>       >>>>     **********************************
       >      >>       >>>>
       >      >>       >>>>     *********************************************************************************************************************************
       >      >>       >>>>     * JOBID    SLOTS    PTILE    HOSTS    USER STATE PRIO        QUEUE        GROUP REMAINING        LIMIT *
       >      >>       >>>>     *********************************************************************************************************************************
       >      >>       >>>>       37489       40       40        1    hutter2 STAGEFAIL
       >      >>       >>>> 550.04       pbatch       guests -     00:30:00
       >      >>       >>>>
       >      >>       >>>>
       >      >>       >>>>     ***************************************************************
       >      >>       >>>>     * HOST_GROUP       TOTAL   DOWN    RSVD   BUSY   FREE   HOSTS *
       >      >>       >>>>     ***************************************************************
       >      >>       >>>>       batch_hosts         16      6       0      0     10 butte[11-26]
       >      >>       >>>>       debug_hosts          2      0       0      0      2 butte[9-10]
       >      >>       >>>>       launch_hosts         1      0       0      0      1 butte[5]
       >      >>       >>>>
       >      >>       >>>>
       >      >>       >>>>     *****************************************************************************************************
       >      >>       >>>>     * QUEUE          TOTAL  DOWN   RSVD/BUSY   FREE DEFAULTTIME MAXTIME  STATE     HOST_GROUP(S) *
       >      >>       >>>>     *****************************************************************************************************
       >      >>       >>>>       exempt            19     6           0     13 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>       expedite          19     6           0     13 30:00      8:00:00 Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>       pall              19     6           0     13 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>       pbatch            17     6           0     11 30:00      8:00:00 Active    launch_hosts,batch_hosts
       >      >>       >>>>       pdebug             3     0           0      3 30:00      1:00:00 Active    launch_hosts,debug_hosts
       >      >>       >>>>       standby           19     6           0     13 None    Unlimited Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>       transfer           1     0           0      1 None    Unlimited
       >      >>       >>>> Active    launch_hosts
       >      >>       >>>>
       >      >>       >>>>> On 3/18/19 2:35 PM, Fox, Dave wrote:
       >      >>       >>>>> I will have to look at around, James did an update on the system over the weekend so it is likely something broke.
       >      >>       >>>>>
       >      >>       >>>>> James, I am in class and have not been watching email, what is your understanding of the status of butte?
       >      >>       >>>>>
       >      >>       >>>>> -----Original Message-----
       >      >>       >>>>> From: Hutter, Tony <hutter2@llnl.gov>
       >      >>       >>>>> Sent: Monday, March 18, 2019 1:49 PM
       >      >>       >>>>> To: Fox, Dave <fox18@llnl.gov>
       >      >>       >>>>> Cc: Gonsiorowski, Elsa <gonsiorowski1@llnl.gov>
       >      >>       >>>>> Subject: Can't reserve node on butte
       >      >>       >>>>>
       >      >>       >>>>> Hi Dave
       >      >>       >>>>>
       >      >>       >>>>> I can't seem to reserve a node on butte anymore.  Any ideas?
       >      >>       >>>>>
       >      >>       >>>>> Thanks
       >      >>       >>>>>
       >      >>       >>>>> -Tony
       >      >>       >>>>>
       >      >>       >>>>> [hutter2@butte5:~]$ bsub -nnodes 1   -stage storage=1 -Is -XF -G guests -core_isolation 2 /usr/tce/packages/lalloc/lalloc-2.0/bin/lexec bash Job <37424> is submitted to default queue <pbatch>.
       >      >>       >>>>> <<ssh X11 forwarding job>>
       >      >>       >>>>> <<Waiting for dispatch ...>>
       >      >>       >>>>>
       >      >>       >>>>>
       >      >>       >>>>> [hutter2@butte5:~]$ lsfjobs -L
       >      >>       >>>>>
       >      >>       >>>>>      **********************************
       >      >>       >>>>>      * Host:    - butte - butte5      *
       >      >>       >>>>>      * Date:    - 03/18/2019 13:46:59 *
       >      >>       >>>>>      * Cmd:     - lsfjobs -L          *
       >      >>       >>>>>      **********************************
       >      >>       >>>>>
       >      >>       >>>>>      *********************************************************************************************************************************
       >      >>       >>>>>      * JOBID    SLOTS    PTILE    HOSTS    USER STATE PRIO QUEUE
       >      >>       >>>>> GROUP REMAINING        LIMIT *
       >      >>       >>>>>      *********************************************************************************************************************************
       >      >>       >>>>>        37424       40       40        1    hutter2 SLOTLIMIT
       >      >>       >>>>> 550.04       pbatch       guests -     00:30:00
       >      >>       >>>>> -----------------------------------------------------------
       >      >>       >>>>>        37414      400       40       10    eckert USUSP
       >      >>       >>>>> -       pbatch       guests            - 00:30:00
       >      >>       >>>>>
       >      >>       >>>>>
       >      >>       >>>>>      ***************************************************************
       >      >>       >>>>>      * HOST_GROUP       TOTAL   DOWN    RSVD   BUSY   FREE HOSTS *
       >      >>       >>>>>      ***************************************************************
       >      >>       >>>>>        batch_hosts         16      6       0     10      0 butte[11-26]
       >      >>       >>>>>        debug_hosts          2      0       0      0      2 butte[9-10]
       >      >>       >>>>>        launch_hosts         1      0       0      1      0 butte[5]
       >      >>       >>>>>
       >      >>       >>>>>
       >      >>       >>>>>      *****************************************************************************************************
       >      >>       >>>>>      * QUEUE          TOTAL  DOWN   RSVD/BUSY   FREE DEFAULTTIME
       >      >>       >>>>> MAXTIME STATE     HOST_GROUP(S) *
       >      >>       >>>>>      *****************************************************************************************************
       >      >>       >>>>>        exempt            19     6          11      2 None Unlimited
       >      >>       >>>>> Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>>        expedite          19     6          11      2 30:00
       >      >>       >>>>> 8:00:00 Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>>        pall              19     6          11      2 None Unlimited
       >      >>       >>>>> Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>>        pbatch            17     6          11      0 30:00
       >      >>       >>>>> 8:00:00 Active    launch_hosts,batch_hosts
       >      >>       >>>>>        pdebug             3     0           1      2 30:00
       >      >>       >>>>> 1:00:00 Active    launch_hosts,debug_hosts
       >      >>       >>>>>        standby           19     6          11      2 None Unlimited
       >      >>       >>>>> Active launch_hosts,batch_hosts,debug_hosts
       >      >>       >>>>>        transfer           1     0           1      0 None Unlimited
       >      >>       >>>>> Active    launch_hosts
       >      >>       >>>>>
       >      >>       >>>>> [hutter2@butte5:~]$ bjobs -l 37424
       >      >>       >>>>>
       >      >>       >>>>> Job <37424>, User <hutter2>, Project <default>, User Group <guests>,
       >      >>       >>>>> Status <PE
       >      >>       >>>>>                          ND>, Queue <pbatch>, Interactive
       >      >>       >>>>> pseudo-terminal shell mod
       >      >>       >>>>>                          e, ssh X11 forwarding mode, Job Priority
       >      >>       >>>>> <5>, Command </us r/tce/packages/lalloc/lalloc-2.0/bin/lexec bash>,
       >      >>       >>>>> Share gr
       >      >>       >>>>>                          oup charged </ROOT/guests/hutter2>, Esub
       >      >>       >>>>> <outfile usergrou
       >      >>       >>>>>                          p bb ptile> Mon Mar 18 13:44:48: Submitted
       >      >>       >>>>> from host <butte5>, CWD <$HOME>, Re-runnable, Re
       >      >>       >>>>>                          quested Resources
       >      >>       >>>>> <1*{select[LN]span[hosts=1]}
       >      >>       >>>>> + 40*{selec
       >      >>       >>>>>                          t[CN]span[ptile=40]}>, Stage requirement
       >      >>       >>>>> requested, Reques
       >      >>       >>>>>                          ted CSM Options <core_isolation=2>; Mon Mar
       >      >>       >>>>> 18
       >      >>       >>>>> 13:47:10: Reserved <1> job slot on host <butte21> for <1> task;
       >      >>       >>>>>      PENDING REASONS:
       >      >>       >>>>>      Job slot limit reached: 10 hosts;
       >      >>       >>>>>
       >      >>       >>>>>      RUNLIMIT
       >      >>       >>>>>      30.0 min
       >      >>       >>>>>
       >      >>       >>>>>      PENDING TIME DETAILS:
       >      >>       >>>>>      Eligible pending time (seconds):    148
       >      >>       >>>>>      Ineligible pending time (seconds):    0
       >      >>       >>>>>
       >      >>       >>>>>      SCHEDULING PARAMETERS:
       >      >>       >>>>>                r15s   r1m  r15m   ut      pg    io   ls it    tmp    swp    mem
       >      >>       >>>>>      loadSched   -     -     -     -       -     -    - -     -      -      -
       >      >>       >>>>>      loadStop    -     -     -     -       -     -    - -     -
       >      >>       >>>>> -
       >      >>       >>>>> -
       >      >>       >>>>>
       >      >>       >>>>>      RESOURCE REQUIREMENT DETAILS:
       >      >>       >>>>>      Combined: 1*{select[(LN) && (type == any)] order[r15s:pg]
       >      >>       >>>>> span[hosts=1]}+40*{s
       >      >>       >>>>>                          elect[(CN) && (type == any)] order[r15s:pg]
       >      >>       >>>>> span[ptile=40]
       >      >>       >>>>>                          }
       >      >>       >>>>>      Effective: -
       >      >>       >>>>>
       >      >>       >>>>>      PLANNED ALLOCATION (Created: Mon Mar 18 13:47:11 2019):
       >      >>       >>>>>      Rank:        1
       >      >>       >>>>>      Start time:  Mon Mar 18 14:17:11 2019
       >      >>       >>>>>      Finish time: Mon Mar 18 14:47:11 2019
       >      >>       >>>>>
       >      >>       >>>>>
       >      >>
       >      >>
       >      
       >

**Comment by tgooding** [comment]
LLNL had some local customizations to the bbactivate script.  Unfortunately, the customizations were based on the CAST 1.4.x level.  This version was being copied over the CAST 1.5 level and thus NVMe over Fabrics was not being setup in a compatible way with the CAST 1.5-based bbProxy.  

Dave added his customizations to the CAST 1.5 version and appears to have resolved the problem.  Long term, Dave was considering making a contribution of the LLNL customizations (as an option) into the official github.  Which would eliminate this sort of problem occurring in the future.

**Comment by tgooding** [comment]
fwiw- the aforementioned local customizations was contributed by LLNL under commit 06f53f9f4cef9e503315de60f9833ac91f92b14b.

**Comment by tgooding** [comment]
Technically invalid and a very old issue:  @gzjfn4 , I think you can close this one.

**Comment by tgooding** [comment]
Stale issue, closing as mentioned above.
