### ISSUE TITLE
csmd utility daemon SEGFAULT on NetworkManager

### ISSUE THREAD

**Issue by fpizzano** [IBM/CAST#65]
Utility daemon SEGFAULT on NetworkManager

```
[UTL]2018-05-17 11:21:38.121519       csmd::info     | CSMD: UTILITY; Build: 1.1.0; Config file: /etc/ibm/csm/csm_utility.cfg
```

```
[UTL]2018-05-20 21:57:45.552520     csmapi::info     | CSM_CMD_node_resources_query_all[1999289472]; Client Recv; PID: 85848; UID:0; GID:0
[UTL]2018-05-20 21:57:45.552602     csmnet::info     | Deleting known client address: tmp/csmi0.85848.20971
[UTL]2018-05-20 21:57:45.552620     csmnet::warning  | Found disconnecting endpoint with pending Accept() of client tmp/csmi0.85848.20971
[UTL]2018-05-20 21:57:45.552689     csmnet::info     | Sync:Active:Endpoint removal: 192.168.75.124:9816  remaining=1
[UTL]2018-05-20 21:57:45.553052       csmd::info     | DAEMONSTATE: DISCONNECTEP: 192.168.75.124:9816
[UTL]2018-05-20 21:57:45.553073       csmd::info     | DAEMONSTATE: UpdateEPStatus(): Status of connection to: 192.168.75.124:9816 change to RUNMODE_DISCONNECTED
[UTL]2018-05-20 21:57:45.553091       csmd::info     | CONN-HDLNG: Removing listening endpoint type:CSM_NETWORK_TYPE_LOCAL addr=/run/csmd.sock
[UTL]2018-05-20 21:57:45.553110     csmnet::info     | ConnectionHandling::TakeDependentDown:Endpoint removal: /run/csmd.sock  remaining=0
[UTL]2018-05-20 21:57:45.553214       csmd::info     | CONN-HDLNG: Transition from RUNMODE_READY_RUNNING to: RUNMODE_DISCONNECTED Reason: ERROR
[UTL]2018-05-20 21:57:45.554662       csmd::critical | Caught segfault when accessing data at address: 0x78
[UTL]2018-05-20 21:57:45.554693       csmd::critical | Instruction Address from where the crash happened: 0x109ad08c
[UTL]2018-05-20 21:57:45.554709       csmd::critical | SEGFAULT: thread_id = 7fff8174f040 handler_name = NetworkManager
```

**Comment by fpizzano** [comment]
Full logs and core @ /ugadmin/csm/CAST/65

```
# ls -l
total 466880
-rw------- 1 root root 106102784 May 21 12:46 core.49727
-rwxr-xr-x 1 root root 125031336 May 21 12:46 csmd
-rw-r--r-- 1 root root   7866844 May 21 12:46 csm_utility.log
```

**Comment by lasch** [comment]
Happens when daemon is in disconnected mode while a timeout check of previous messages hits a msg from a local client.
The local socket is torn down when going to disconnected mode to prevent new clients from trying to access the daemon. Missed a check for a torn-down socket before processing check on timed-out messages.
Fix is on the way...

**Comment by lasch** [comment]
Testing this will be pretty tough. It'll take at least:
* a utilitity daemon connected to master
* a request from a client process
* the right timing that causes a disconnect between master and utility while the client has not responded to the API response with an ACK

* Creating the missing ACK from the client should be easy by suspending the process with SIGSTOP.
* I suggest to use something like ```error_inject -t 10```  to create clients that have to wait for 10s before getting a response. That gives you a 10s window to SIGSTOP these clients to prevent the ACK
* the tricky part is to make the ACK timeout and the daemon disconnect appear at the same time. Maybe there's a way to increase the probability of hitting it by running several client processes concurrently and starting them at slightly different times.
* getting the utility daemon into disconnected mode can be done by:
  * stop the master
  * pull the network cable
  * suspend the master

I keep thinking about this and will comment if I come up with a better way to test this.

**Comment by lasch** [comment]
Did we ever see this happening again after the candidate fix?

**Comment by fpizzano** [comment]
Closing, no re-occurrence after the fix.
