### ISSUE TITLE
burst buffer: request to raise RAS events on failed create LV

### ISSUE THREAD

**Issue by adammoody** [IBM/CAST#655]
**Summary:**
At times due to various system issues, the BB fails to create the logical volume on a host.  This often leaves the host in a bad state.  We'd like the BB software to generate RAS events in these cases so that the host can automatically be drained out of the set of available hosts. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Issue Source:**
Reasoning for opening this issue; a description of why this issue was opened; a link to another thread that spawned the need for opening this issue.

**Comment by dlherms-ibm** [comment]
Solution to be provided will have a RAS event raised for any failure of an admin level BB command or API.  BB create LV operations are admin level, so RAS events will be raised for any create LV failure.

Code being worked...

**Comment by tgooding** [comment]
This should be in verify state.

**Comment by tgooding** [comment]
BB admin command failure RAS has been verified, closing
