### ISSUE TITLE
Too many json files in /var/log/ibm/csm/archive

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#679]
There are far too many *.json files in /var/log/ibm/csm/archive, and I'm now hitting a limit in filebeat.  I can see if there is a way to increase the limit, but it really doesn't make sense to have filebeat monitoring old files that are not intended to every have new data.

We need some strategy to improve this situation.

**Comment by thanh-lam** [comment]
I just looked on my cluster. There are lots of empty (0 file size) files. Every time the archive command is run, many db tables don't have any activities in their history. Again, maybe that's just on my cluster. In this case, the first thing I'd do is to remove all the empty files to reduce the number of files. But, it's not going to save any space.

**Comment by morrone** [comment]
Yes, there are many empty files.  CSM should probably stop doing that.

I'm less concerned about space in this ticket than I am about the shear number of files.  The large number (over 5000) is causing issues already.

**Comment by williammorrison2** [comment]
@morrone we are working on a solution to rectify this current situation.

**Comment by mew2057** [comment]
I have implemented a first pass fix for this issue. I've implemented a script which collates existing json into weekly slices. We might want to make the baseline archive script slice the data into weekly files as well, removing the need for the script in the future. Additionally, I've modified the filebeat to close files after they've been moved or set to inactive.

**Comment by besawn** [comment]
I think this was resolved via #688, please reopen if you are still experiencing this issue.
