### ISSUE TITLE
For BB failover, cannot restart transfer definition with only remote CP operations

### ISSUE THREAD

**Issue by dlherms-ibm** [IBM/CAST#692]
With the current support, a transfer definition with only remote cp file operation(s) cannot be successfully restarted after a failover to another bbServer.  The handle for such a transfer definition will remain in the BBSTOPPED state after such a failover attempt.

A possible circumvention is to include any other type of file operation in a transfer definition that only has remote cp.  File operations of local cp, transfer of file to SSD, transfer of file from SSD included in such a transfer definition will allow the transfer definition to be successfully restarted after a failover to another bbServer.

**Comment by tgooding** [comment]
Don't think we'll address restart opportunities of this corner case.
