### ISSUE TITLE
csmd error "Could not determine size [of SSD]" in csm_compute.log

### ISSUE THREAD

**Issue by thanh-lam** [IBM/CAST#945]
**Describe the bug**
After starting csmd-compute and dcgm on a compute node, following error message was in `/var/log/ibm/csm/csm_compute.log`:
```
[root@f10n15 csm]# grep -i ":err" csm_compute.log
[COMPUTE]2020-08-07 09:26:21.318079       csmd::error    | Error: could not determine size
```

As besawn@us.ibm.com pointed out, this turned out to be an issue "related to NVME/SSD inventory, not GPUs. The problem seems to be that the NVME device names are different on RHEL8 than RHEL7, so inventory collection is failing to find the size correctly.

**To Reproduce**
1. As root, check to see if dcgm service is running: `systemctl status dcgm`
2. If not running, start the dcgm service: `systemctl start dcgm`
3. Check to see if csmd-compute is service is running: `systemctl status csmd-compute`
4. If not running, start csmd-compute service: `systemctl start csmd-compute`
4. Check `/var/log/ibm/csm/csm_compute.log` for errors

**Expected behavior**
There shouldn't be this kind of errors in csm_compute.log.

**Environment (please complete the following information):**
 - IST BDS cluster: f4n05 (csm master), f10n15-16 (compute nodes)
 - CSM 1.8.1

**Additional context**

**Issue Source:**
CSM & DCGM upgrade regression.

**Comment by besawn** [comment]
This problem is blocking proper cluster operation in a customer environment - raising severity to reflect this.

**Comment by besawn** [comment]
This problem can also be observed by checking the `size` field of the `ssd` records in the output of `csm_node_attributes_query_details`:
```
/opt/ibm/csm/bin/csm_node_attributes_query_details -n c650f99p26
...
  ssds_count:                   1
  ssds:
    - serial_number:                 S3RVNA0K400104
      update_time:                   2020-08-17 11:07:49.865951
      device_name:                   PCIe3 1.6TB NVMe Flash Adapter II x8
      fw_ver:                        MN12MN12
      pci_bus_id:                    0030:01:00.0
      size:                          -1
      wear_lifespan_used:            0.000000
      wear_total_bytes_read:         4817353728000
      wear_total_bytes_written:      3748815360000
      wear_percent_spares_remaining: 100.000000
...
```
size equal to -1 is an error

**Comment by besawn** [comment]
Having the SSD size reported as -1 then leads to failures when attempting to allocate space on that SSD using `csm_bb_vg_create`:

```
[csmapi][error] csmi_sendrecv_cmd failed: 25 - csm_bb_vg_create[1318132869]; Database Error Message: error_handling_test: P0001/Requested space on ssd serial number: S3RVNA0K400104 is greater than its size
```

**Comment by tgooding** [comment]
> seems to be that the NVME device names are different on RHEL8 than RHEL7

Has this statement been proven/disproven?  We don't use the nvme driver out of RHEL (it comes from MLNX) and the naming conventions seem to me to be the same.

**Comment by besawn** [comment]
An efix to CSM 1.8.1 is available that contains a fix to this issue. The cluster that was blocked by this issue has reported that the efix has allowed them to progress past this problem. Lowering severity to reflect current status.

**Comment by besawn** [comment]
@thanh-lam This issue is fixed in the current builds of CSM. Can you verify the fix in your test environment and close this issue if your tests pass successfully?

**Comment by thanh-lam** [comment]
I just checked most of the compute nodes on IST CORAL clusters and didn't see the error message about "could not determine size" in csm_compute.log anymore.

The csm node attribute details command shows these nodes don't have SSD:
```
[root@c685f4n07 bin]# ./csm_node_attributes_query_details -n f10n15 | grep -i ssd
  node_discovered_ssds:         0
  ssds_count:                   0
```
I think that's correct -- the nodes don't have SSD. Will see if I can find a compute node with SSD and run the command.

**Comment by thanh-lam** [comment]
Verified on nodes that have SSD or NVMe and got correct info about SSDs. For example:

# /opt/ibm/csm/bin/csm_node_attributes_query_details -n f10n15
...
ssds:
    - serial_number:                 S3RVNA0J300511
      update_time:                   2020-09-22 12:08:17.943611
      device_name:                   PCIe3 1.6TB NVMe Flash Adapter II x8
      fw_ver:                        MN12MN12
      pci_bus_id:                    0000:01:00.0
      size:                          1600321314816
      wear_lifespan_used:            0.000000
      wear_total_bytes_read:         3200989184000
      wear_total_bytes_written:      2491903488000
      wear_percent_spares_remaining: 100.000000

Closing.
